### ISSUE TITLE
Copy Paste (Clipboard) Keyboard Shortcut Issue

### ISSUE THREAD

**Issue by matthewmullin01** [tauri-apps/tauri#1055]
I have noticed that using the keyboard shortcuts (`cmd/ctrl-c` and `cmd/ctrl-v`) to copy or paste text from a input field does not work.

I have however seen that using the right click context menu works as expected.

_Note I am on MacOS 11_.

**To Reproduce**

1. Download and Install official Tauri example app from https://tauri.studio/en/docs/get-started/setup-macos
2. Run App
3. Go to `Communication` tab
4. Enter text in the text box
5. Notice that you cannot select all copy or paste using keyboard shortcuts.

**Screenshots**
![image](https://user-images.githubusercontent.com/19774189/96348115-90823500-10a6-11eb-9779-9989de636e17.png)

**Platform and Versions (please complete the following information):**

OS: Mac OS 11
Node: v12.18.3
NPM: 6.14.6
Yarn: 0.1.0
Rustc: 1.46.0 (04488afe3 2020-08-24)

**Comment by lucasfernog** [comment]
Hmm I thought https://github.com/webview/webview/pull/405 would fix this. @abeMedia do you know something about this?

**Comment by virtualgraham** [comment]
I have the same issue, also ctrl z does not undo text input like it does in the browser.

**Comment by abemedia** [comment]
@lucasfernog that PR only allows clipboard access from JS. You still need to write the JS event to capture it.

**Comment by matthewmullin01** [comment]
Thanks for the leads. Don't know how I didn't find anything related to this when searching.

For those wondering the solution is to listen for a copy or paste event and simply call `document.execCommand('copy');` or `document.execCommand('paste');`

_Rudimentary vue example below._

```vue
<template>
  <Editor @keydown.meta.86="pasteEvent()" @keydown.meta.67="copyEvent()"  ... />
</template>

<script>
// ...
  copyEvent() {
    document.execCommand('copy');
  }

  pasteEvent() {
    document.execCommand('paste');
  }
// ...
</script>
```

**Comment by virtualgraham** [comment]
@matthewmullin01 The cmd-c copy event works fine. The cmd-v paste event causes a content menu to appear with a paste option that you still have to click on to actually paste. Also there is a system beep that needs to be prevented by calling event.preventDefault(). This is on Mac.

**Comment by nklayman** [comment]
Just for reference, everything works as intended on Linux.

**Comment by nklayman** [comment]
This has been fixed in the dev branch of Tauri and will be available in the next release.

**Comment by lukeed** [comment]
I'm still seeing the contextmenu show up on `paste` while using macOS and `tauri@1.0.0-beta.1`

Not sure if this version was the "next release"

**Comment by AlexHayton** [comment]
I'm also seeing the same behaviour... :(
This is on 1.0.0-beta.2

**Comment by serkandemirel0420** [comment]
I have still the problem and also beeps. yes, it beeps. Even in textbox, cmd+a not possible.

**Comment by gdotdesign** [comment]
I'm running into the same issue.

**Comment by FabianLars** [comment]
For shurtcuts like this to work **on macos** you need to add a window menu. See #2397 for more or this [template](https://github.com/probablykasper/tauri-template/blob/master/src-tauri/src/main.rs) for inspiration.

The beeping sound is also known, see #2626. Unfortunetly we haven't found a solution so far.

**Comment by gdotdesign** [comment]
@FabianLars thank you!

**Comment by gdotdesign** [comment]
Managed to make it work with the A menu as you suggested but with some differences because the template used not sable API.

```rust
let about_menu = Submenu::new("App", Menu::new()
  .add_native_item(MenuItem::Hide)
  .add_native_item(MenuItem::HideOthers)
  .add_native_item(MenuItem::ShowAll)
  .add_native_item(MenuItem::Separator)
  .add_native_item(MenuItem::Quit));

let edit_menu = Submenu::new("Edit", Menu::new()
  .add_native_item(MenuItem::Undo)
  .add_native_item(MenuItem::Redo)
  .add_native_item(MenuItem::Separator)
  .add_native_item(MenuItem::Cut)
  .add_native_item(MenuItem::Copy)
  .add_native_item(MenuItem::Paste)
  .add_native_item(MenuItem::SelectAll));

let view_menu = Submenu::new("View", Menu::new()
  .add_native_item(MenuItem::EnterFullScreen));

let window_menu = Submenu::new("Window", Menu::new()
  .add_native_item(MenuItem::Minimize)
  .add_native_item(MenuItem::Zoom));

let help_menu = Submenu::new("Help", Menu::new()
  .add_item(CustomMenuItem::new("Learn More", "Learn More")));

let menu = Menu::new()
  .add_submenu(about_menu)
  .add_submenu(edit_menu)
  .add_submenu(view_menu)
  .add_submenu(window_menu)
  .add_submenu(help_menu);

app
.menu(menu)
.on_menu_event(|event| {
  let event_name = event.menu_item_id();
  match event_name {
    "Learn More" => {
      shell::open(
        "https://www.my-app.com".to_string(),
        None,
      )
      .unwrap();
    }
    _ => {}
  }
})
```

Let it be known that there are some not specified menu items show up (probably the OS adds them???). Also, this should be added to the official documentation at some point :)
