### ISSUE TITLE
[bug] Can't move or resize the main window

### ISSUE THREAD

**Issue by uAtomicBoolean** [tauri-apps/tauri#10686]
### Describe the bug

I can't move or resize a window after upgrading to tauri latest rc (`2.0.0-rc.3` at that time) when running as dev.  
The thing is it doesn't come from that tauri version as downgrading it doesn't solve the problem.  

### Reproduction

1. Create a minimal tauri app using the latest release candidate.  
`cargo create-tauri-app --rc`

2. Run the app in dev mode.
`cargo tauri dev`

### Expected behavior

Be able to move or resize the application's window.

### Full `tauri info` output

```text
WARNING: no lock files found, defaulting to npm

[✔] Environment
    - OS: Fedora 40.0.0 X64
    ✔ webkit2gtk-4.1: 2.44.2
    ✔ rsvg2: 2.57.1
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.6.0
    - npm: 10.8.1
    - bun: 1.1.24

[-] Packages
    - tauri [RUST]: 2.0.0-rc (no lockfile)
    - tauri-build [RUST]: no manifest (no lockfile)
    - wry [RUST]: no manifest (no lockfile)
    - tao [RUST]: no manifest (no lockfile)
    - tauri-cli [RUST]: 2.0.0-rc.3
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src
```

**Comment by loafman1120** [comment]
I got the same promble, with the newest RC version. My system information is "Manjaro Arch24 with gnome+wayland".
I've upgrade everything.

**Comment by loafman1120** [comment]
I found some special things, I install the gtk3 library(pacman -S gtk3 in the "tao" doc),now I can move the window in the "dev" option, but I still can't move the windows in "build" option.

**Comment by loafman1120** [comment]
![图片](https://github.com/user-attachments/assets/d12ec08a-ff90-4eed-b5b1-d4ea7329d515)
This is the difference besides "build"(left, can't move) and "build"(right, can move)

**Comment by loafman1120** [comment]
I did something more, I found that if I right-click the botton on the titile bar, I can move it.

**Comment by uAtomicBoolean** [comment]
Found something kind of similar, when clicking and holding on the minimize or close buttons, I can move the window.

Also, here is the output of the `cargo update` that introduces this bug, if that can help:
```
Updating crates.io index
     Locking 82 packages to latest compatible versions
      Adding adler2 v2.0.0
    Updating arrayvec v0.7.4 -> v0.7.6
    Updating async-io v2.3.3 -> v2.3.4
    Updating async-process v2.2.3 -> v2.2.4
    Updating async-signal v0.2.9 -> v0.2.10
    Updating brotli v3.5.0 -> v6.0.0
    Updating brotli-decompressor v2.5.1 -> v4.0.1
    Updating bytemuck v1.16.3 -> v1.17.0
    Updating camino v1.1.7 -> v1.1.9
    Updating cc v1.1.8 -> v1.1.13
      Adding cocoa v0.26.0
      Adding cocoa-foundation v0.2.0
      Adding core-foundation v0.10.0
    Updating core-foundation-sys v0.8.6 -> v0.8.7
      Adding core-graphics v0.24.0
      Adding core-graphics-types v0.2.0
    Updating cpufeatures v0.2.12 -> v0.2.13
    Updating flate2 v1.0.31 -> v1.0.32
      Adding fluent-uri v0.1.4 (latest: v0.2.0)
    Updating indexmap v2.3.0 -> v2.4.0
    Updating js-sys v0.3.69 -> v0.3.70
    Updating json-patch v1.4.0 -> v2.0.0
      Adding jsonptr v0.4.7 (latest: v0.6.0)
    Updating libc v0.2.155 -> v0.2.158
      Adding miniz_oxide v0.8.0
    Updating mio v1.0.1 -> v1.0.2
    Updating muda v0.13.5 -> v0.14.1
    Updating ndk v0.7.0 -> v0.9.0
    Updating ndk-sys v0.4.1+23.1.7779620 -> v0.6.0+11769913
    Updating num_enum v0.5.11 -> v0.7.3
    Updating num_enum_derive v0.5.11 -> v0.7.3
    Updating piper v0.2.3 -> v0.2.4
    Updating polling v3.7.2 -> v3.7.3
    Removing raw-window-handle v0.5.2
    Updating redox_users v0.4.5 -> v0.4.6
    Updating reqwest v0.12.5 -> v0.12.7
    Updating rkyv v0.7.44 -> v0.7.45
    Updating rkyv_derive v0.7.44 -> v0.7.45
    Updating rust_decimal v1.35.0 -> v1.36.0
    Updating serde v1.0.205 -> v1.0.208
    Updating serde_derive v1.0.205 -> v1.0.208
    Updating serde_json v1.0.122 -> v1.0.125
      Adding shlex v1.3.0
    Updating syn v2.0.72 -> v2.0.75
    Updating tao v0.28.1 -> v0.29.1
    Updating tao-macros v0.1.2 -> v0.1.3
    Updating tauri v2.0.0-rc.1 -> v2.0.0-rc.5
    Updating tauri-build v2.0.0-rc.1 -> v2.0.0-rc.5
    Updating tauri-codegen v2.0.0-rc.1 -> v2.0.0-rc.5
    Updating tauri-macros v2.0.0-rc.1 -> v2.0.0-rc.5
    Updating tauri-plugin v2.0.0-rc.1 -> v2.0.0-rc.5
    Updating tauri-plugin-dialog v2.0.0-rc.0 -> v2.0.0-rc.2
    Updating tauri-plugin-log v2.0.0-rc.0 -> v2.0.0-rc.1
    Updating tauri-plugin-shell v2.0.0-rc.0 -> v2.0.0-rc.2
    Updating tauri-runtime v2.0.0-rc.1 -> v2.0.0-rc.5
    Updating tauri-runtime-wry v2.0.0-rc.1 -> v2.0.0-rc.5
    Updating tauri-utils v2.0.0-rc.1 -> v2.0.0-rc.5
    Updating tokio v1.39.2 -> v1.39.3
    Updating tower-layer v0.3.2 -> v0.3.3
    Updating tower-service v0.3.2 -> v0.3.3
    Updating tray-icon v0.14.3 -> v0.15.1
    Updating typeid v1.0.0 -> v1.0.2
    Updating unicode-properties v0.1.1 -> v0.1.2
    Updating wasm-bindgen v0.2.92 -> v0.2.93
    Updating wasm-bindgen-backend v0.2.92 -> v0.2.93
    Updating wasm-bindgen-futures v0.4.42 -> v0.4.43
    Updating wasm-bindgen-macro v0.2.92 -> v0.2.93
    Updating wasm-bindgen-macro-support v0.2.92 -> v0.2.93
    Updating wasm-bindgen-shared v0.2.92 -> v0.2.93
    Updating web-sys v0.3.69 -> v0.3.70
    Updating webview2-com v0.31.0 -> v0.33.0
    Updating webview2-com-macros v0.7.0 -> v0.8.0
    Updating webview2-com-sys v0.31.0 -> v0.33.0
    Updating window-vibrancy v0.5.0 -> v0.5.1
    Updating windows v0.57.0 -> v0.58.0
    Updating windows-core v0.57.0 -> v0.58.0
    Updating windows-implement v0.57.0 -> v0.58.0
    Updating windows-interface v0.57.0 -> v0.58.0
      Adding windows-registry v0.2.0
    Updating windows-result v0.1.2 -> v0.2.0
      Adding windows-strings v0.1.0
    Updating wry v0.41.0 -> v0.42.0
    Updating xdg-home v1.2.0 -> v1.3.0
note: pass `--verbose` to see 125 unchanged dependencies behind latest
```

**Comment by uAtomicBoolean** [comment]
The issue might come from `tauri-runtime-wry`. I've found that adding it to the `Cargo.toml` to set it to its last version (`2.0.0-rc.6`) brings the bug.  

Also, both minimize and close buttons work and I can move the window when "dragging" them.  

```
[✔] Environment
    - OS: Fedora 40 X64
    ✔ webkit2gtk-4.1: 2.44.2
    ✔ rsvg2: 2.57.1
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 22.6.0
    - npm: 10.8.1
    - bun: 1.1.24

[-] Packages
    - tauri [RUST]: 2.0.0-rc.1
    - tauri-build [RUST]: 2.0.0-rc.1
    - wry [RUST]: 0.42.0
    - tao [RUST]: 0.29.1
    - tauri-cli [RUST]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:3000/

```

**Comment by loafman1120** [comment]
so that we should tell it to the "wry" project. I'm not good at the cases, can you please donging some tests and tell them?

**Comment by vlabo** [comment]
It also happens in release mode.
For some reason this is specific for Gnome + Wayland

KDE + X11 -> Can resize and move
KDE + Wayland -> Can resize and move
GNOME + X11 -> Can resize and move
 GNOME + Wayland -> The issue appears.

**Comment by tram98** [comment]
Can confirm this bug on Fedora Workstation 40.
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
Kernel: Linux 6.10.6-200.fc40.x86_64
DE: GNOME 46.4
WM: Mutter (Wayland)

**Comment by akrpic77** [comment]
Same here.

I can move the window if I grab it by minimize/maximize/close button. 

Debian sid. Gnome wayland.

[✔] Environment
    - OS: Debian n/a x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.44.3
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.11.1
    - npm: 9.9.3

[-] Packages
    - tauri 🦀: 2.0.0-rc.8
    - tauri-build 🦀: 2.0.0-rc.7
    - wry 🦀: 0.42.0
    - tao 🦀: 0.29.1
    - @tauri-apps/api : 2.0.0-rc.4
    - @tauri-apps/cli : 2.0.0-rc.8

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : 2.0.0-rc.1
    - tauri-plugin-updater 🦀: 2.0.0-rc.2
    - @tauri-apps/plugin-updater : 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist-tauri
    - devUrl: http://localhost:3000/
    - framework: Vue.js
    - bundler: Rollup

I found out that [window](https://github.com/tauri-apps/tao/blob/dev/examples/window.rs) example in tao doesn't allow to move/resize window either, but in [drag_window](https://github.com/tauri-apps/tao/blob/dev/examples/drag_window.rs) example it is possible to move windows (but not resize - it's the example's purpose to show how to make window movable by holding on edges).

**Comment by loafman1120** [comment]
As you tell. I also found that you can hold down three buttons, such as the minimize button, to move the window.
Something interesting

**Comment by amrbashir** [comment]
It seems to me that this problem is caused by Ubuntu on Wayland and nothing we can do to fix this on our side since we simply use GTK3 to create the window and it handles resizing on it self. 

If there is other GTK3 apps (non-tauri) that exhibits this behavior, then it is probably a bug in Ubuntu on Wayland.

**Comment by Khalid-Nowaf** [comment]
same issue here on debain 12,  when I run 
`npm run tauri dev`

``` logs
Couldn't get key from code: Unidentified(Gtk(248))
Couldn't get key from code: Unidentified(Gtk(248))
```

**Comment by akrpic77** [comment]
using [xprop method](https://superuser.com/a/1792349) of detecting if  application is running native wayland or thru xwayland (shows crosshair on xwayland and no cursor change on wayland). I have found out:

- Running my app uses native wayland, move/resize DOESN'T work
- Running my app with GDK_BACKEND=wayland uses native wayland, move/resize DOESN'T work
- Running my app with GDK_BACKEND=x11 uses xwayland, move/resize works
- Running gtk's [example/application1](https://gitlab.gnome.org/GNOME/gtk/-/tree/main/examples/application1?ref_type=heads) with GDK_BACKEND=x11 uses xwayland, move/resize works
- Running gtk's [example/application1](https://gitlab.gnome.org/GNOME/gtk/-/tree/main/examples/application1?ref_type=heads) with GDK_BACKEND=wayland uses native wayland, **move/resize DOES work**

This suggests that the problem is in tauri/tao/wry and not in the system.

My current workaround is setting env var "GDK_BACKEND" to x11 at top of the main() function.

p.s. beware of running your app from vs code terminal as it sets GDK_BACKEND to x11

**Comment by amrbashir** [comment]
Thanks @akrpic77 for the investigation, I will see if I we are doing something finky in our code once I get my linux machine setup. 

I still don't understand why would KDE+Wayland work but not Gnome+Wayland.

**Comment by Khalid-Nowaf** [comment]
I have built a release .**deb** and .**AppImage**.

 the .**AppImage** works fine with resizing and moving, since it shipped with all dependencies and does not use any system libs.

**Comment by FabianLars** [comment]
The appimage also forces `GDK_BACKEND=x11` though.

**Comment by ndom91** [comment]
I've gone through and tried all `tauri-runtime-wry` versions from `rc.8` back down to `rc.2` and it seems that it really has broken in `rc.3`, that was the first release where my app also began experiencing these issues in wayland+gnome DE's

**Comment by akrpic77** [comment]
following on hint by @ndom91, I found out that reversing changes of [fix(linux): prevent firing duplicate mouse events](https://github.com/tauri-apps/tao/commit/e67cf1b2826d32b8eb58f6d111271a1c42b62978) in tao fixes move/size issue, but brings back duplicate mouse events.

**Comment by Khalid-Nowaf** [comment]
> following on hint by @ndom91, I found out that reversing changes of [fix(linux): prevent firing duplicate mouse events](https://github.com/tauri-apps/tao/commit/e67cf1b2826d32b8eb58f6d111271a1c42b62978) in tao fixes move/size issue, but brings back duplicate mouse events.

I think this is relevant, because I managed to move the window one time by holding the click for some time. But I did not know how to produce it again.

**Comment by goenning** [comment]
based on all the comments above, this is the hacky fix I have, which seems to work. 

If you have a better solution, please share :)

```rust
if env::var("APPIMAGE").is_ok() || std::env::var("FLATPAK_ID").is_ok() {
    return;
}

let desktop = env::var("XDG_CURRENT_DESKTOP").unwrap_or_default().to_lowercase();
if desktop.contains("gnome") {
    env::set_var("GDK_BACKEND", "x11");
}
```

**Comment by ndom91** [comment]
Tauri 2 includes the ability to pass a .desktop file template for deb and rpm. So we decided to do something similar ^^ and prefix `env GDK_BACKEND=x11` before the preexisting `Exec=` key contents

**Comment by fogzot** [comment]
Using the X11 backend is not a solution, it is a hack. I hope this can be fixed in TAO.

**Comment by ndom91** [comment]
> Using the X11 backend is not a solution, it is a hack. I hope this can be fixed in TAO.

Right, but it's a workaround for now for folks that made the migration to Tauri v2 already and don't want to go back

**Comment by Khalid-Nowaf** [comment]
This issue is blocking me from releasing my app (the app is not usable). Are we expecting a fix in the upcoming releases?

**Comment by Zamoca42** [comment]
@Khalid-Nowaf  I have implemented a header for Wayland, and it will be included in the next version once https://github.com/tauri-apps/tao/pull/982 is released.

**Comment by amrbashir** [comment]
Closed by https://github.com/tauri-apps/tao/pull/979, if the issue happens after release, please let me know

**Comment by nekename** [comment]
I'm still getting this in my app OpenDeck after updating to the stable release.

Edit: it's the same behaviour, I'm on GNOME + Wayland, and I can move the window by dragging the decoration buttons, and can't resize.

**Comment by amrbashir** [comment]
@ninjadev64 apologies, we forgot to release the `tao` dependency, I have released it now, run `cargo update -p tao` in `src-tauri` and see if the issue is fixed.

**Comment by fogzot** [comment]
@amrbashir i tested the new release and that's not really a solution. The custom header has 2 serious problems:

1. the header does not follow the platform theme (light/dark);
2. the size of the window is wrong because the header height is not taken into account. This means that the available area is different between platforms with Linux Wayland getting less vertical space than, for example, Windows.

Please, reopen this bug report until a proper fix is implemented.

**Comment by Zamoca42** [comment]
> 2\. the size of the window is wrong because the header height is not taken into account. This means that the available area is different between platforms with Linux Wayland getting less vertical space than, for example, Windows.

In my opinion, this is a separate issue. There was already a problem with the window not being created accurately even before the custom header.

see: https://github.com/tauri-apps/tao/issues/929

**Comment by fogzot** [comment]
@Zamoca42 I didn't note that when using the RC versions that still had the bug (and the native headerbar?). Anyway the current situation under Linux/Wayland is terrible.

**Comment by nekename** [comment]
> @ninjadev64 apologies, we forgot to release the `tao` dependency, I have released it now, run `cargo update -p tao` in `src-tauri` and see if the issue is fixed.

Seems to be fixed, thanks.

**Comment by yuezk** [comment]
I found the root cause of this issue when troubleshooting the issue https://github.com/tauri-apps/tao/issues/929. Adding a comment here for future reference.

It turns out to be an issue of the GTK or Wayland under certain scenarios.

By tracking the history, I found that this issue was introduced by #941, which is trying to fix the duplicated mouse event triggered by a single click on Linux. The solution in this PR is to prevent the related event from being propagated.

Since the issue is Wayland-specific. I reproduced this issue with a minimal GTK app using the `gtk-rs` crate.

```rust
use gtk::{glib, prelude::*};
use gtk::{Application, ApplicationWindow};

fn main() {
  let app = Application::builder()
    .application_id("org.example.HelloWorld")
    .build();

  app.connect_activate(|app| {
    // We create the main window.
    let win = ApplicationWindow::builder()
      .application(app)
      .default_width(320)
      .default_height(320)
      .title("Hello, World!")
      .build();

    win.connect_button_press_event(|_win, event| {
      dbg!(event);
      glib::Propagation::Stop
    });

    win.show_all();
  });

  app.run();
}
```

On Wayland, running the above code directly will cause the window to not move. If you run the code with `GDK_BACKEND=x11` (i.e., XWayland is used) or on X11, the window can move.

The reason is that clicking on the window title bar will trigger a button press event on Wayland, and the `connect_button_press_event` callback stops the event. So the window cannot move. However, on XWayland or X11, clicking on the window title bar will not trigger a button press event, so the window can move.

So, this could be a bug in GTK or Wayland. I have reported it at: https://gitlab.gnome.org/GNOME/gtk/-/issues/7327

----

BTW, using `GDK_BACKEND=x11` will use XWayland on the Wayland environment. If you enable Tauri's tray icon, this will cause the two system tray icons (one is active, another is dead) problem.
