### ISSUE TITLE
[feat] Improve error message for forbidden paths during dev

### ISSUE THREAD

**Issue by itsMapleLeaf** [tauri-apps/tauri#11338]
### Describe the problem

This error message shows in the browser console when an FS operation fails due to a disallowed path:

> "forbidden path C:\whatever\..."

It turns out I was missing the "fs:allow-exists" permission, but the error message didn't give me any clue about that, and it made me think something elsewhere else was broken 😅 

### Describe the solution you'd like

The error message should be more specific:

> missing the 'fs:allow-exists' permission for this path: C:\whatever\...

**Comment by ayangweb** [comment]
https://github.com/tauri-apps/plugins-workspace/issues/1927#issuecomment-2408996385 This might help.

**Comment by itsMapleLeaf** [comment]
> [tauri-apps/plugins-workspace#1927 (comment)](https://github.com/tauri-apps/plugins-workspace/issues/1927#issuecomment-2408996385) This might help.

My issue is already resolved, I'm specifically suggesting to improve an error message I encountered

**Comment by KyleBrown-804** [comment]
When do the capabilities get re-checked? I was missing the same but even after adding `fs:allow-exists` and restarting the app in dev mode, I still have the same issue

**Comment by KyleBrown-804** [comment]
Okay if anyone else runs into this, it seems like you (**must?**) also include an allowed scope for the permissions. One example I found in the docs is buried under "Scopes" at the very bottom of the page: https://v2.tauri.app/plugin/file-system/#examples.

I don't see any mention of the `allow` being required and the permission itself in the docs reads: `"Enables the exists command without any pre-configured scope."`. So I'm not sure if this is a bug or just bad documentation but removing `allow` causes forbidden path for any exists check in the home dir but putting `allow` back in fixes it.

This allows the `fs:allow-exists` permission for the home directory and anything under it.
```
{
    "identifier": "fs:allow-exists",
    "allow": [{ "path": "$HOME" }, { "path": "$HOME/**/*" }]
}
```

More practically since I don't want to copy / paste this for every single fs permission, the following _should_ allow all fs scope permissions under a directory:
```
{
    "identifier": "fs:scope",
    "allow": [{ "path": "$HOME" }, { "path": "$HOME/**/*" }]
}
```
