### ISSUE TITLE
[feat] IOS/Android SafeArea control

### ISSUE THREAD

**Issue by lnB51** [tauri-apps/tauri#11475]
### Describe the problem

Hello everyone, I've encountered a problem while developing an iOS app. An annoying white titlebar appeared at the top of the screen and on both left and right on landscapre mode. 

![зображення](https://github.com/user-attachments/assets/a7b13912-c328-49ff-94eb-bd3abad53042)

Most likely, the issue is related to this: https://developer.apple.com/documentation/swiftui/view/ignoressafearea(_:edges:)

If that's the case, it might be useful to implement a feature in Tauri that allows control over this parameter.

### Describe the solution you'd like

Now swiftUI offers a function to disable it, it would be nice to have something similar in Tauri.

```swift
struct ContentView: View {
    var body: some View {
        NavigationView {
            ZStack {
                LinearGradient(
                    colors: [.red, .yellow],
                    startPoint: .topLeading,
                    endPoint: .bottomTrailing
                )
                .ignoresSafeArea()
                .navigationTitle("Hello World")
            }
        }
    }
}
```
<div align="center">
  
| Before `.ignoresSafeArea()` | After `.ignoresSafeArea()` |
|-----------------------------|----------------------------|
| <img width="182" alt="Before" src="https://github.com/user-attachments/assets/9939dd43-9f8b-4b91-ac8c-83531930adb0"> | <img width="177" alt="After" src="https://github.com/user-attachments/assets/3fd00c60-e124-4e5e-b9fb-cee51d5ee475"> |

</div>

**Comment by philippremy** [comment]
While I agree that it would be nice to have this in the official documentation, it seems that the only way to achieve this is by editing/adding a HTML meta-tag in the HTML file: `viewport-fit=cover`. 
You can then pad the relevant HTML elements using CSSs `env()` function with the following values: `safe-area-inset-top` and `safe-area-inset-bottom`

This is described with an example in #6961.

**Comment by lnB51** [comment]
Initially tried to handle ```safe-area paddings``` with the ```meta``` tag and the ```@capacitor-community/safe-area ``` plugin combined with Tailwind, but it only worked on iOS. For Android, I used enableEdgeToEdge() and managed the paddings manually using:
```css
max(var(--safe-area-inset-bottom), 20px)
```

**Comment by lnB51** [comment]
I think it would be nice to have this implemented for both Android and IOS. I changed the issue topic.

**Comment by alexwohlbruck** [comment]
chiming in here. i can attest that the `viewport-fit=cover` attribute works well on iOS, along with the CSS safe-area
 inset variables. Although, i'm having some issues getting it to actually discover these insets until i focus a text input for some reason

Android, however, doesn't respect the viewport fit attribute. When using the transparent status bar theme, I can't find any way to make the app ui adapt to the safe area padding

<img height="500" alt="Image" src="https://github.com/user-attachments/assets/56b52cc2-b9e2-4af1-a5a5-cf36ceda58a7" />

<img height="500" alt="Image" src="https://github.com/user-attachments/assets/d5f353b1-9343-492c-adca-f1b69987fa13" />

```
<resources xmlns:tools="http://schemas.android.com/tools">
  <!-- Base application theme. -->
  <style name="Theme.app" parent="Theme.MaterialComponents.DayNight.NoActionBar">
    <!-- Status bar and Navigation bar configurations -->
    <item name="android:statusBarColor">@android:color/transparent</item>
    <item name="android:navigationBarColor">@android:color/transparent</item>
    <item name="android:windowLightStatusBar">false</item>
    <item name="android:windowLightNavigationBar" tools:targetApi="27">false</item>
    <item name="android:windowTranslucentStatus">true</item>
    <item name="android:windowTranslucentNavigation">true</item>
    <item name="android:enforceNavigationBarContrast" tools:targetApi="29">false</item>
    <item name="android:windowLayoutInDisplayCutoutMode" tools:targetApi="o_mr1">shortEdges</item>
  </style>
</resources>
```

**Comment by 6xingyv** [comment]
```
//App.vue
<script setup lang="js">
</script>

<template>
  <div class="text-black dark:text-white h-[100vh] select-none dark:bg-red-200">
    <div class="pt-[env(safe-area-inset-top)] pb-[env(safe-area-inset-bottom)]">
      <h1 class="text-4xl">Hello World</h1>
      <div class="bg-red-500 h-full">
      </div>
    </div>
  </div>
</template>

<style>
@import "tailwindcss";
</style>
```

```
//src-tauri\gen\android\app\src\main\java\com\mocharealm\books\MainActivity.kt
package com.mocharealm.books

import android.os.Bundle
import android.view.WindowInsets
import android.webkit.JavascriptInterface
import android.webkit.WebView
import androidx.activity.enableEdgeToEdge

class MainActivity : TauriActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    enableEdgeToEdge()
  }
}
```
This works for me on Android.
![Image](https://github.com/user-attachments/assets/5449bb09-b639-4a2c-bb77-f1ca7b438aac)

@alexwohlbruck try and see if it works

**Comment by setoelkahfi** [comment]
Got the problem on Android now after updating Tauri.

**Comment by reifenrath-dev** [comment]
Also got the same problem with Android target API 35. The insets work as expected on the emulator using Android 15 and 16, but on the real devices all insets stay 0.

**Comment by yourplansGit** [comment]
Same problem with Android target API 35.

**Comment by FabianLars** [comment]
Can you check the webview version in the system settings or user agent on the device where it's not working? Wondering if it's the regression in 139: https://issues.chromium.org/issues/441253216 (fixed for 140 - edit: or maybe not: https://issues.chromium.org/issues/40699457#comment71)

**Comment by yourplansGit** [comment]
Fixed On WebView version 140 
Thank you for help.

**Comment by reifenrath-dev** [comment]
I had a version of WebView 140 were it was still an issue. Spend a lot of time debugging and could not make sense of it. Today I got an update for WebView to version 140.0.7339.51.0 and NOW it works on my device, too. Just wanted to add this info before someone else spends their time debugging for this ghost of a bug.

**Comment by kj-9** [comment]
On Android, I tried using https://github.com/ronickg/tauri-plugin-safe-area-insets, and it works great for handling bottom insets.

**Comment by LinboLen** [comment]
### options 1

```java
package xxx


import android.os.Bundle
import android.webkit.WebView
import androidx.core.view.ViewCompat
import androidx.core.view.WindowCompat
import androidx.core.view.WindowInsetsCompat
import kotlin.math.roundToInt

class MainActivity : TauriActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    // Enable edge-to-edge display for SafeArea support
    // WindowCompat.setDecorFitsSystemWindows(window, false)
  }

  override fun onWebViewCreate(webView: WebView) {
    super.onWebViewCreate(webView)

    ViewCompat.setOnApplyWindowInsetsListener(webView) { _, insets ->
      val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
      val displayCutout = insets.getInsets(WindowInsetsCompat.Type.displayCutout())

      val density = resources.displayMetrics.density

      val safeTop = maxOf(systemBars.top, displayCutout.top)
      val safeBottom = maxOf(systemBars.bottom, displayCutout.bottom)
      val safeLeft = maxOf(systemBars.left, displayCutout.left)
      val safeRight = maxOf(systemBars.right, displayCutout.right)

      val script = """
            document.documentElement.style.setProperty('--safe-area-inset-top', '${(safeTop / density).roundToInt()}px');
            document.documentElement.style.setProperty('--safe-area-inset-bottom', '${(safeBottom / density).roundToInt()}px');
            document.documentElement.style.setProperty('--safe-area-inset-left', '${(safeLeft / density).roundToInt()}px');
            document.documentElement.style.setProperty('--safe-area-inset-right', '${(safeRight / density).roundToInt()}px');
        """.trimIndent()

      webView.evaluateJavascript(script, null)
      insets
    }
  }
}
```

### options 2. (recommend)
```java
package xxx

import android.os.Bundle
import android.view.View
import android.webkit.WebView
import androidx.activity.enableEdgeToEdge
import androidx.activity.result.contract.ActivityResultContracts
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat

class MainActivity : TauriActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    enableEdgeToEdge()
    super.onCreate(savedInstanceState)

    val rootView: View = findViewById(android.R.id.content)

    ViewCompat.setOnApplyWindowInsetsListener(rootView) { v, insets ->
      val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
      val imeVisible = insets.isVisible(WindowInsetsCompat.Type.ime())
      val imeHeight = insets.getInsets(WindowInsetsCompat.Type.ime()).bottom
  
      val bottomPadding = if (imeVisible) imeHeight else systemBars.bottom
      
      v.setPadding(
          systemBars.left,
          systemBars.top,
          systemBars.right,
          bottomPadding
      )
      insets
    }

  }

  override fun onWebViewCreate(webView: WebView) {
    super.onWebViewCreate(webView)

    webView.setBackgroundColor(0x00000000)
    
    webView.fitsSystemWindows = true

    android.util.Log.i("MainActivity", "WebView created, waiting for Rust hide() call...")
  }
}
```
