### ISSUE TITLE
[bug] In Android MainActivity is leaked if a foreground service is running and makes the app unusable on next launch

### ISSUE THREAD

**Issue by mohit92** [tauri-apps/tauri#11609]
### Describe the bug

It seems that Tauri Android app don't expect the application process to outlive the MainActivity, which is common in android world if you are running a foreground service

In this case when you relaunch the app, Tauri has two instances of MainActivity and RustWebview which causes __TAURI_INVOKE_KEY__ mismatch causing the app to become unsuable.

### Reproduction

Download and build the [sample project](https://github.com/m-byondlabs/screenshare-mobile-tauri). Please build it in release mode, as the repro steps require killing the app. Be sure to add your release key and configure local.properties to set up signing keys. Link to the repo: https://github.com/m-byondlabs/screenshare-mobile-tauri

Launch the app, click the "Start Share" button, and allow the prompt to start screen sharing.

You should see a screencast icon indicating that the foreground service is actively capturing the screen recording.

Swipe up to close the MainActivity; you’ll notice that the foreground service continues capturing the screen (this is intended and expected behavior).

Reopen the app and click "Start Share" or "Stop Share." You will observe a log indicating a __TAURI_INVOKE_KEY__ mismatch.

If you generate a heap dump, you’ll find two instances of MainActivity, meaning the previous activity is leaked and remains in memory.

I've verified that my code does not retain any references to the activity, so it appears that the Tauri Plugin manager or another code path in Tauri may be holding onto that instance.

### Expected behavior

Once the activity is destroyed, it should not stay in the memory 

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.6.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.17.0
    - npm: 10.8.2

[-] Packages
    - tauri 🦀: 2.0.4
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.1
    - tao 🦀: 0.30.3
    - tauri-cli 🦀: 2.0.2
    - @tauri-apps/api : 2.0.2 (outdated, latest: 2.0.3)
    - @tauri-apps/cli : 2.0.2 (outdated, latest: 2.0.4)

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.0 (outdated, latest: 2.0.1)

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by lucasfernog** [comment]
we're creating a [global reference](https://docs.rs/jni/latest/jni/objects/struct.GlobalRef.html) to the activity [here](https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/android/ndk_glue.rs#L202) so we probably need to find a way to clean it up.

**Comment by lucasfernog** [comment]
the problem with the invoke keys is [wry statics](https://github.com/tauri-apps/wry/blob/7c4f2b7299d408234b7ea67e6cb82a680e945764/src/android/mod.rs#L63) which is a lifecycle issue in this case - since your app is still open in the foreground, the Rust code is still running - and the process is reused when the app is reopened.

**Comment by lucasfernog** [comment]
i'm trying some changes for the memory leak, no luck yet.

**Comment by lucasfernog** [comment]
I think i've fixed it. If you wanna early try it,  add the following to the Cargo.toml file:

```toml
[patch.crates-io]
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "dev" }
tauri-plugin = { git = "https://github.com/tauri-apps/tauri", branch = "dev" }
tauri-build = { git = "https://github.com/tauri-apps/tauri", branch = "dev" }
tao = { git = "https://github.com/tauri-apps/tao", branch = "fix/android-leak" }
wry = { git = "https://github.com/lucasfernog/wry", branch = "fix/android" }
```

(to validate if the patches are properly applied, you can see if there's no `[patch.unused]` in the cargo.lock file

**Comment by tracy-codes** [comment]
@lucasfernog fyi ever since https://github.com/tauri-apps/wry/pull/1414 there have been reports of android apps crashing due to Borrow errors.

Please look into https://github.com/tauri-apps/wry/issues/1420

**Comment by DrunkenToast** [comment]
> [@lucasfernog](https://github.com/lucasfernog) fyi ever since [tauri-apps/wry#1414](https://github.com/tauri-apps/wry/pull/1414) there have been reports of android apps crashing due to Borrow errors.
> 
> Please look into [tauri-apps/wry#1420](https://github.com/tauri-apps/wry/issues/1420)

Comments on this issue mentioned it being fixed in 0.50, am I correct to assume that this issue has been resolved?

**Comment by DrunkenToast** [comment]
It sadly seems like this issue is still open, I still have the `__TAURI_INVOKE_KEY__ expected X but received Y` errors when reopening an app that has a foreground service running.

**Comment by ahqsoftwares** [comment]
A workaround is to turn on the brownfield pattern

**Comment by ahqsoftwares** [comment]
Also, this is fixed

**Comment by FabianLars** [comment]
> A workaround is to turn off the brownfield pattern

This makes no sense to me. What do you mean by that?

**Comment by ahqsoftwares** [comment]
> > A workaround is to turn off the brownfield pattern
> 
> This makes no sense to me. What do you mean by that?

Just realized I said to turn off brownfield pattern, when i meant to turn it on 

I meant this one [brownfield](https://tauri.app/concept/inter-process-communication/brownfield)

**Comment by FabianLars** [comment]
Hmm I assume most are using that over the isolation pattern.

**Comment by FabianLars** [comment]
> It sadly seems like this issue is still open, I still have the __TAURI_INVOKE_KEY__ expected X but received Y errors when reopening an app that has a foreground service running.

Does that actually cause issues though?

**Comment by ahqsoftwares** [comment]
Also seems like the pull requests have been merged in tao and wry. So isn't it fixed already?

**Comment by FabianLars** [comment]
@DrunkenToast's message was after all related PRs were merged so apparently not? Maybe fixing the memory leak didn't include fixing the invoke key and whatever else is broken.

OP's reproduction does not exist anymore so a new one would be appreciated :)

**Comment by DrunkenToast** [comment]
Hey Lars!

I am afraid I won't be able to get the reproduction anymore since I am not working on the project anymore.
However the issue was definitely still there!

I am fairly sure you could make it happen by having a background service that could launch the main activity and closing the app, then reopening it with the service still there. Something along those lines. It seemed like there were 2 references to the main activity at the same time.
And it did cause crashes and unintended behaviour.

I worked around it by forcefully closing the service when the app closes with lifecycle listeners. Which I thought was an alright solution but it wasn't perfect. If in any case the service was still active and the app was closed, the app would be completely unusable.

I made a background location plugin which worked fine but only with the lifecycle listeners.

**Comment by FabianLars** [comment]
Thanks for the prompt reaction. I'll leave this issue open then - i can't work on this myself so idk how long it'll stay open either x)

**Comment by DrunkenToast** [comment]
I won't be able to share the full project code but I found a few incomplete snippets that I can share.
The lifecycles I added were necessary or the app would get in a broken state.
Last time I ran it, it was on latest (I even checked out a branch with another fix I believe, which didn't help). So for me it definitely wasn't fixed.

In my opinion is it normal that you can't really launch the app like that anymore when the app is closed and a service is lingering but devs shouldn't have to deal with an app ending up in a broken state when you do though :)

The code is incomplete and fairly poorly written but hopefully it is enough to create a reproduction from, really hope it helps! :)

```kotlin
class ExamplePlugin(private val activity: Activity) : Plugin(activity) {
    private lateinit var implementation: Example
    private var locationService: LocationService? = null
    private var watchers = hashMapOf<Long, Pair<Invoke, WatchArgs>>()

    private val connection = object : ServiceConnection {
        override fun onServiceConnected(className: ComponentName?, service: IBinder?) {
            Log.i("App", "DEBUG: start called + service connected")
            val binder = service as LocationService.LocalBinder
            locationService = binder.getService()
            locationService?.watchers = watchers
            locationService?.activityToLaunch = activity::class.java
        }

        override fun onServiceDisconnected(arg0: ComponentName?) {
            locationService?.watchers = null
        }
    }

    // Location service commands
    @SuppressLint("NewApi")
    @Command
    fun start(invoke: Invoke) {
        Log.i("App", "DEBUG: start called")
        val args = invoke.parseArgs(StartArgs::class.java)
        var t = Intent(activity.applicationContext, LocationService::class.java).apply {
            action = LocationService.ACTION_START
            putExtra("totalDistance", args.totalDistance)
            activity.startForegroundService(this)
        }
        activity.bindService(t, connection, Context.BIND_ADJUST_WITH_ACTIVITY);
        invoke.resolve()
    }

    @SuppressLint("NewApi")
    @Command
    fun stop(invoke: Invoke) {
        Log.i("App", "DEBUG: stop called")
        Intent(activity.applicationContext, LocationService::class.java).apply {
            action = LocationService.ACTION_STOP
            activity.startForegroundService(this)
        }
        invoke.resolve()
    }

    @Command
    fun watchDistance(invoke: Invoke) {
        Log.i("App", "DEBUG: watch distance!" + this.locationService.toString())
        val args = invoke.parseArgs(WatchArgs::class.java)
        startWatch(invoke, args)
        invoke.resolve()
    }

    private fun startWatch(invoke: Invoke, args: WatchArgs) {
        watchers[args.channel.id] = Pair(invoke, args)
    }

    @Command
    fun clearWatch(invoke: Invoke) {
        val args = invoke.parseArgs(ClearWatchArgs::class.java)
        watchers.remove(args.channelId)
        invoke.resolve()
    }
}


class AppLifecycleTracker(private var activity: Activity) : ActivityLifecycleCallbacks {
    override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) {}

    override fun onActivityStarted(activity: Activity) {}

    override fun onActivityResumed(activity: Activity) {}

    override fun onActivityPaused(activity: Activity) {}

    override fun onActivityStopped(activity: Activity) {}

    override fun onActivitySaveInstanceState(activity: Activity, outState: Bundle) {}

    // NOTE: See https://github.com/tauri-apps/tauri/issues/11609
    // We destroy the service ourselves so that the application doesn't linger
    // causing issues on next launch
    @RequiresApi(Build.VERSION_CODES.O)
    override fun onActivityDestroyed(activity: Activity) {
        Intent(activity.applicationContext, LocationService::class.java).apply {
            action = LocationService.ACTION_STOP
            activity.startForegroundService(this)
        }
        activity.stopService(Intent(activity.applicationContext, LocationService::class.java))
    }
}
```

```kotlin

class LocationService() : Service() {
    var totalDistance: Float = 0f
        private set

    val distanceJSObject: JSObject
        get() {
            val ret = JSObject()
            ret.put("totalDistance", this.totalDistance)
            return ret
        }

    var watchers: HashMap<Long, Pair<Invoke, WatchArgs>>? = null
    var activityToLaunch: Class<out Activity>? = null
    private var isForeground = false
    private val binder = LocalBinder()

    inner class LocalBinder : Binder() {
        // Return this instance of LocalService so clients can call public methods.
        fun getService(): LocationService = this@LocationService
    }


    private val serviceScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private lateinit var locationClient: LocationClient
    override fun onBind(p0: Intent?): IBinder {
        return binder
    }

    override fun onCreate() {
        super.onCreate()
        locationClient =
            LocationClient(
                applicationContext,
                LocationServices.getFusedLocationProviderClient(applicationContext)
            )
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        Log.i("App", "DEBUG: Start command intent for service")
        when (intent?.action) {
            ACTION_START -> {
                val totalDistance = intent.extras?.getFloat("totalDistance")
            }

            ACTION_STOP -> stop()
        }
        return super.onStartCommand(intent, flags, startId)
    }

    @SuppressLint("InlinedApi")
    private fun start(
        totalDistance: Float, milestoneTarget: Float, milestoneProgress: Float
    ) {
        this.totalDistance = totalDistance
        notifyWatchers()

        if (isForeground) return

        val notification =
            NotificationCompat.Builder(this, LOCATION_CHANNEL)
                .setContentTitle("Tracking Location")
                .setContentText("Location: null")
                .setSmallIcon(R.drawable.ic_media_play)
                .setOngoing(true)
                .setSilent(true)
        val notificationManager =
            getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager

        notificationManager?.notify(1, notification.build())

        var prevLocation: Location? = null;

        locationClient
            .getLocationUpdates(10L)
            .catch { e -> e.printStackTrace() }
            .onEach {
                val distanceMoved = prevLocation?.distanceTo(it) ?: 0f
                this.totalDistance += distanceMoved

                // Notification update
                val lat = it.latitude.toString()
                val long = it.longitude.toString()
                notification.setContentText("Location: ($lat, $long)")
                notificationManager?.notify(1, notification.build())

                notifyWatchers()
                prevLocation = it;
            }
            .launchIn(serviceScope)

        startForeground(1, notification.build(), ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE)
        isForeground = true
    }

    @SuppressLint("NewApi")
    private fun stop() {
        if (isForeground) {
            serviceScope.cancel()
            stopForeground(STOP_FOREGROUND_DETACH)
            stopSelf()
            val notificationManager =
                getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
            notificationManager.cancel(1)
            isForeground = false
        }
    }

    private fun notifyWatchers() {
        this.watchers?.forEach { (_, watcherData) ->
            val channel = watcherData.second.channel
            channel.send(this.distanceJSObject)
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        serviceScope.cancel()
    }

    companion object {
        const val ACTION_START = "ACTION_START"
        const val ACTION_STOP = "ACTION_STOP"
    }
}
```

**Comment by FabianLars** [comment]
thanks again, really appreciate that!

**Comment by ahqsoftwares** [comment]
I am currently writing an app that will utilize foreground service quite soon. I think it'll be done by a few weeks and then I can test it myself if it bugs out

**Comment by ahqsoftwares** [comment]
# DEBUG APP
It partially works when running a foreground service. Basically the app does not load correctly if you cold start the activity. But if you start it after closing the activity. It works 

![Screenshot_20250727-210620_AHQ Store.jpg](https://github.com/user-attachments/assets/bb6b577e-ba3a-44d8-b39a-52f7d2de5130)

![Screenshot_20250727-210742_AHQ Store.jpg](https://github.com/user-attachments/assets/d2d70338-1e68-4ee9-83d0-8cbbef7a19e4)

**Comment by ahqsoftwares** [comment]
I'm building a release build to test

**Comment by ahqsoftwares** [comment]
```
2025-07-27 21:11:50.730 15057-15057 DecorView               com.ahqstore.app                     I  [INFO] isPopOver=false, config=true
2025-07-27 21:11:50.731 15057-15057 DecorView               com.ahqstore.app                     I  updateCaptionType >> DecorView@4af0ae1[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
2025-07-27 21:11:50.731 15057-15057 DecorView               com.ahqstore.app                     D  setCaptionType = 0, this = DecorView@4af0ae1[]
2025-07-27 21:11:50.745 15057-15057 DecorView               com.ahqstore.app                     I  getCurrentDensityDpi: from real metrics. densityDpi=280 msg=resources_loaded
2025-07-27 21:11:50.832 15057-15057 ViewRootIm...nActivity] com.ahqstore.app                     I  setView = com.android.internal.policy.DecorView@4af0ae1 TM=true
2025-07-27 21:11:50.922 15057-15057 ViewRootIm...nActivity] com.ahqstore.app                     I  Relayout returned: old=(0,0,720,1600) new=(0,0,720,1600) req=(720,1600)0 dur=55 res=0x7 s={true 4121916416} ch=true fn=-1
2025-07-27 21:11:50.930 15057-15162 OpenGLRenderer          com.ahqstore.app                     D  eglCreateWindowSurface
2025-07-27 21:11:50.934 15057-15057 ViewRootIm...nActivity] com.ahqstore.app                     I  [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11420 android.view.ViewRootImpl.performTraversals:4193 android.view.ViewRootImpl.doTraversal:2919 
2025-07-27 21:11:50.934 15057-15057 ViewRootIm...nActivity] com.ahqstore.app                     D  Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
2025-07-27 21:11:50.935 15057-15057 ViewRootIm...nActivity] com.ahqstore.app                     D  Creating frameCompleteCallback
2025-07-27 21:11:50.943 15057-15298 ViewRootIm...nActivity] com.ahqstore.app                     D  Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
2025-07-27 21:11:50.950 15057-15162 ViewRootIm...nActivity] com.ahqstore.app                     D  Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
2025-07-27 21:11:50.954 15057-15057 Tauri/Plugin            com.ahqstore.app                     V  Tauri plugin: pluginId: path, command: getCacheDir
2025-07-27 21:11:50.958 15057-15057 ViewRootIm...nActivity] com.ahqstore.app                     I  [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4995 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
2025-07-27 21:11:50.958 15057-15057 ViewRootIm...nActivity] com.ahqstore.app                     I  [DP] rdf()
2025-07-27 21:11:50.958 15057-15057 ViewRootIm...nActivity] com.ahqstore.app                     D  reportDrawFinished (fn: -1) 
2025-07-27 21:11:50.959 15057-15057 InsetsSourceConsumer    com.ahqstore.app                     D  ensureControlAlpha: for ITYPE_NAVIGATION_BAR on com.ahqstore.app/com.ahqstore.app.MainActivity
2025-07-27 21:11:50.961 15057-15057 InsetsSourceConsumer    com.ahqstore.app                     D  ensureControlAlpha: for ITYPE_STATUS_BAR on com.ahqstore.app/com.ahqstore.app.MainActivity
2025-07-27 21:11:50.978 15057-15057 Tauri/Plugin            com.ahqstore.app                     V  Tauri plugin: pluginId: deep-link, command: setEventHandler
2025-07-27 21:11:51.009 15057-15057 ViewRootIm...nActivity] com.ahqstore.app                     I  MSG_WINDOW_FOCUS_CHANGED 1 1
2025-07-27 21:11:51.011 15057-15057 InputMethodManager      com.ahqstore.app                     D  startInputInner - Id : 0
2025-07-27 21:11:51.011 15057-15057 InputMethodManager      com.ahqstore.app                     I  startInputInner - mService.startInputOrWindowGainedFocus
2025-07-27 21:11:52.068 15057-15057 Tauri/Console           com.ahqstore.app                     E  File: http://tauri.localhost/static/js/vendors-node_modules_pnpm_fluentui_react-icons_2_0_306_react_18_3_1_node_modules_fluentui_rea-596b74.js - Line 31008 - Msg: [HMR] WebSocket connection error, attempting direct fallback.
2025-07-27 21:11:53.747 15057-32556 RustStdoutStderr        com.ahqstore.app                     I  [INFO] Running Desktop Setup
2025-07-27 21:11:53.747 15057-32556 RustStdoutStderr        com.ahqstore.app                     I  [INFO] Running
2025-07-27 21:11:53.957 15057-15057 Enqueued                com.ahqstore.app                     W  Periodic Work Running
2025-07-27 21:11:53.965 15057-15057 Enqueued                com.ahqstore.app                     W  Periodic Work Registered
2025-07-27 21:11:56.779 15057-15057 Tauri/Console           com.ahqstore.app                     I  File: http://tauri.localhost/static/js/vendors-node_modules_pnpm_fluentui_react-icons_2_0_306_react_18_3_1_node_modules_fluentui_rea-596b74.js - Line 31000 - Msg: [HMR] disconnected. Attempting to reconnect.
```

**Comment by ahqsoftwares** [comment]
The logs are during the point when the activity doesn't load

**Comment by ahqsoftwares** [comment]
# Release Build

Absolutely no issues


## Conclusion

The issue has been fixed successfully

**Comment by DrunkenToast** [comment]
I'd argue that if things don't work as expected in debug mode it isn't resolved.
Developers are gonna worry or debug hours for why something isn't working as expected.

**Comment by ahqsoftwares** [comment]
Though also I am using rsbuild and in console logs the reason the app
doesn't run in that activity is due to hmr error. So, it's not in the scope
of tauri itself

**Comment by ahqsoftwares** [comment]
![Screenshot_20250728-074033_GitHub.jpg](https://github.com/user-attachments/assets/b87f63ff-706c-491b-87a0-a7f7fefc1126)

Here

**Comment by DrunkenToast** [comment]
Oh I see, in that case it would be resolved.  
I just recall that in my case the screen would completely white and the app would be unresponsive with the error log: `__TAURI_INVOKE_KEY__ expected ...`

If it doesn't happen anymore then no point in keeping the issue open.

**Comment by FabianLars** [comment]
hmm let's close it for now then and re-open if needed :)
