### ISSUE TITLE
[bug] macOS: App crashes on startup after successful cargo tauri build --target universal-apple-darwin

### ISSUE THREAD

**Issue by handexing** [tauri-apps/tauri#13996]
### Describe the bug

On macOS, I can successfully build my Tauri application using
cargo tauri build --target universal-apple-darwin
without any error messages during the build process.
However, when I try to launch the built application, it immediately crashes.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 15.5.0 x86_64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.87.0 (17067e9ac 2025-05-09)
    ✔ cargo: 1.87.0 (99624be96 2025-05-06)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 20.12.2
    - pnpm: 9.15.1
    - yarn: 1.22.5
    - npm: 10.5.2

[-] Packages
    - tauri 🦀: 2.7.0
    - tauri-build 🦀: 2.3.1
    - wry 🦀: 0.52.1
    - tao 🦀: 0.34.0
    - tauri-cli 🦀: 2.5.0 (outdated, latest: 2.7.1)
    - @tauri-apps/api : 2.7.0
    - @tauri-apps/cli : 2.7.1

[-] Plugins
    - tauri-plugin-http 🦀: 2.0.0, (outdated, latest: 2.5.1)
    - @tauri-apps/plugin-http : 2.0.0
    - tauri-plugin-autostart 🦀: 2.5.0
    - @tauri-apps/plugin-autostart : not installed!
    - tauri-plugin-shell 🦀: 2.3.0
    - @tauri-apps/plugin-shell : 2.3.0
    - tauri-plugin-single-instance 🦀: 2.3.2
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-updater 🦀: 2.9.0
    - @tauri-apps/plugin-updater : 2.9.0
    - tauri-plugin-dialog 🦀: 2.3.2
    - @tauri-apps/plugin-dialog : 2.3.2
    - tauri-plugin-process 🦀: 2.3.0
    - @tauri-apps/plugin-process : 2.3.0
    - tauri-plugin-global-shortcut 🦀: 2.3.0
    - @tauri-apps/plugin-global-shortcut : 2.2.0
    - tauri-plugin-log 🦀: 2.6.0
    - @tauri-apps/plugin-log : 2.6.0
    - tauri-plugin-clipboard-manager 🦀: 2.3.0
    - @tauri-apps/plugin-clipboard-manager : 2.3.0
    - tauri-plugin-store 🦀: 2.3.0
    - @tauri-apps/plugin-store : not installed!
    - tauri-plugin-fs 🦀: 2.4.1
    - @tauri-apps/plugin-fs : 2.4.1
```

### Stack trace

```text
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               芒果云创作 [13369]
Path:                  /Applications/芒果云创作.app/Contents/MacOS/芒果云创作
Identifier:            com.mango.cloud
Version:               1.3.2 (1.3.2)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2025-08-13 16:56:11.1942 +0800
OS Version:            macOS 15.5 (24F74)
Report Version:        12
Bridge OS Version:     9.5 (22P5072)
Anonymous UUID:        D4684E1C-A2C6-A2BC-CC24-F46D4F94A9DE

Sleep/Wake UUID:       9128DF30-E704-48BD-B65A-2C9924E5882E

Time Awake Since Boot: 21000 seconds
Time Since Wake:       12284 seconds

System Integrity Protection: enabled

Crashed Thread:        0  main  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [13369]

VM Region Info: 0 is not in any region.  Bytes before following region: 4355964928
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      103a2c000-1076a2000    [ 60.5M] r-x/r-x SM=COW  /Applications/芒果云创作.app/Contents/MacOS/芒果云创作

Thread 0 Crashed:: main Dispatch queue: com.apple.main-thread
0   CoreFoundation                	    0x7ff80571ea24 CF_IS_OBJC + 8
1   CoreFoundation                	    0x7ff8055def46 CFStringGetLength + 60
2   CoreFoundation                	    0x7ff8055e1f36 CFStringFindWithOptionsAndLocale + 76
3   CoreFoundation                	    0x7ff8055e1ed2 CFStringHasPrefix + 55
4   CoreFoundation                	    0x7ff8056e0d98 __CFBundleCopyFrameworkURLForExecutablePath + 456
5   CoreFoundation                	    0x7ff80563f28c _CFBundleEnsureBundleExistsForImagePath + 19
6   CoreFoundation                	    0x7ff8056f3174 _CFBundleGetBundleWithIdentifier + 194
7   Foundation                    	    0x7ff806744aa6 +[NSBundle bundleWithIdentifier:] + 27
8   芒果云创作                         	       0x1049963ea objc2_foundation::generated::__NSBundle::NSBundle::bundleWithIdentifier::h253b1ed1e050c806 + 42
9   芒果云创作                         	       0x10492a600 wry::wkwebview::platform_webview_version::hb9b91d811afe6d6d + 48
10  芒果云创作                         	       0x1049345de wry::webview_version::hde2cb6b03a0583bf + 14
11  芒果云创作                         	       0x103fc912d _$LT$tauri_runtime_wry..Wry$LT$T$GT$$u20$as$u20$tauri_runtime..Runtime$LT$T$GT$$GT$::new::h2531c2391a7d348c + 1421
12  芒果云创作                         	       0x103d5ff69 tauri::app::Builder$LT$R$GT$::run::h0e308aebf171b4a2 + 937
13  芒果云创作                         	       0x104157b2a mango_cloud_app_lib::main::h0eb9c1213bdd2d20 + 2938
14  芒果云创作                         	       0x103a2d056 std::sys::backtrace::__rust_begin_short_backtrace::haf7f69fd950d2fba + 6
15  芒果云创作                         	       0x103a2d04c std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h35d844152020e1a5 + 12
16  芒果云创作                         	       0x104efa9ae std::rt::lang_start_internal::ha4af94bb3c6aded2 + 814
17  芒果云创作                         	       0x103a2d0ac main + 44
18  dyld                          	    0x7ff8051c5530 start + 3056

Thread 1:: r2d2-worker-0
0   libsystem_kernel.dylib        	    0x7ff80552b6f6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff80556b27a _pthread_cond_wait + 988
2   芒果云创作                         	       0x104b3300a parking_lot::condvar::Condvar::wait_until_internal::hdf942318cf576c96 + 682
3   芒果云创作                         	       0x104b2f69f scheduled_thread_pool::Worker::run::h32379fadda013a63 + 111
4   芒果云创作                         	       0x104b30073 std::sys::backtrace::__rust_begin_short_backtrace::hc8c0664ec5cb5a10 + 19
5   芒果云创作                         	       0x104b316b3 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h5f83fbf7ddcd8680 + 179
6   芒果云创作                         	       0x104f0adab std::sys::pal::unix::thread::Thread::new::thread_start::h7feb70d0ed1fab2c + 43
7   libsystem_pthread.dylib       	    0x7ff80556adf1 _pthread_start + 99
8   libsystem_pthread.dylib       	    0x7ff805566857 thread_start + 15

Thread 2:: r2d2-worker-1
0   libsystem_kernel.dylib        	    0x7ff80552b6f6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff80556b27a _pthread_cond_wait + 988
2   芒果云创作                         	       0x104b3300a parking_lot::condvar::Condvar::wait_until_internal::hdf942318cf576c96 + 682
3   芒果云创作                         	       0x104b2f69f scheduled_thread_pool::Worker::run::h32379fadda013a63 + 111
4   芒果云创作                         	       0x104b30073 std::sys::backtrace::__rust_begin_short_backtrace::hc8c0664ec5cb5a10 + 19
5   芒果云创作                         	       0x104b316b3 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h5f83fbf7ddcd8680 + 179
6   芒果云创作                         	       0x104f0adab std::sys::pal::unix::thread::Thread::new::thread_start::h7feb70d0ed1fab2c + 43
7   libsystem_pthread.dylib       	    0x7ff80556adf1 _pthread_start + 99
8   libsystem_pthread.dylib       	    0x7ff805566857 thread_start + 15

Thread 3:: r2d2-worker-2
0   libsystem_kernel.dylib        	    0x7ff80552b6f6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff80556b27a _pthread_cond_wait + 988
2   芒果云创作                         	       0x104b3300a parking_lot::condvar::Condvar::wait_until_internal::hdf942318cf576c96 + 682
3   芒果云创作                         	       0x104b2f69f scheduled_thread_pool::Worker::run::h32379fadda013a63 + 111
4   芒果云创作                         	       0x104b30073 std::sys::backtrace::__rust_begin_short_backtrace::hc8c0664ec5cb5a10 + 19
5   芒果云创作                         	       0x104b316b3 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h5f83fbf7ddcd8680 + 179
6   芒果云创作                         	       0x104f0adab std::sys::pal::unix::thread::Thread::new::thread_start::h7feb70d0ed1fab2c + 43
7   libsystem_pthread.dylib       	    0x7ff80556adf1 _pthread_start + 99
8   libsystem_pthread.dylib       	    0x7ff805566857 thread_start + 15

Thread 4:
0   libsystem_pthread.dylib       	    0x7ff805566834 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	    0x7ff805566834 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	    0x7ff805566834 start_wqthread + 0


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x1ffcc9eb203c0001  rbx: 0x0000000000000000  rcx: 0x0000000000000008  rdx: 0x0000000000000000
  rdi: 0x0000000000000007  rsi: 0x0000000000000000  rbp: 0x00007ff7bc4cbbf0  rsp: 0x00007ff7bc4cbbd8
   r8: 0x0000000000000008   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x00007ff8057f4900
  r12: 0x0000000000000008  r13: 0x00007ff7bc4cca70  r14: 0x0000600002020210  r15: 0x0000000000000008
  rip: 0x00007ff80571ea24  rfl: 0x0000000000010246  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Thread 0 instruction stream:
  2c 83 c7 b8 8b 15 fa ce-a6 41 39 d7 7d 31 89 fa  ,........A9.}1..
  c1 fa 06 48 63 d2 48 8d-35 e7 cd a6 41 48 8b 94  ...Hc.H.5...AH..
  d6 80 00 00 00 48 85 d2-74 15 83 e7 3f 48 8d 14  .....H..t...?H..
  fa 48 8b 12 48 39 d1 75-08 31 c0 0f b6 c0 c3 31  .H..H9.u.1.....1
  d2 f6 c1 01 74 f5 48 8b-05 c7 c6 fc 3d 48 23 08  ....t.H.....=H#.
  48 39 d1 0f 95 c0 eb e3-b0 01 40 f6 c6 01 75 6e  H9........@...un
 [48]8b 0e 48 85 c9 74 1e-48 83 ff 07 75 09 48 3b  H..H..t.H...u.H;	<==
  0d 8f 76 86 41 74 55 48-83 ff 47 77 17 48 8d 15  ..v.AtUH..Gw.H..
  88 ce a6 41 eb 3a 48 85-ff 74 41 55 48 89 e5 e8  ...A.:H..tAUH...
  6b 32 09 00 83 c7 b8 8b-15 67 ce a6 41 39 d7 7d  k2.......g..A9.}
  31 89 fa c1 fa 06 48 63-d2 48 8d 35 54 cd a6 41  1.....Hc.H.5T..A
  48 8b 94 d6 80 00 00 00-48 85 d2 74 15 83 e7 3f  H.......H..t...?

Binary Images:
       0x103a2c000 -        0x1076a1fff com.mango.cloud (1.3.2) <eab44a5d-35bf-3f8c-a7b9-d7353ffce081> /Applications/芒果云创作.app/Contents/MacOS/芒果云创作
    0x7ff8055d8000 -     0x7ff805a8cff2 com.apple.CoreFoundation (6.9) <2f3a4185-6038-37d0-a02b-ec620bcd977b> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff806739000 -     0x7ff80752a8b1 com.apple.Foundation (6.9) <3e72de1d-c81a-3c8b-9c06-5b1e3186de47> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7ff8051bf000 -     0x7ff805259527 dyld (*) <3771ea6a-0fe5-3b63-961d-c09e01d5e680> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff805528000 -     0x7ff805564b4f libsystem_kernel.dylib (*) <dab10aa4-8afa-3d02-9cde-6023554ac858> /usr/lib/system/libsystem_kernel.dylib
    0x7ff805565000 -     0x7ff805570dcf libsystem_pthread.dylib (*) <a6d1f05a-0743-31b7-9fe2-268f06ccd51a> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=853.2M resident=0K(0%) swapped_out_or_unallocated=853.2M(100%)
Writable regions: Total=652.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=652.3M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          160K       23 
CoreServices                       236K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           635.7M       84 
MALLOC guard page                   48K       12 
STACK GUARD                         24K        6 
Stack                             15.5M        7 
Stack Guard                       56.0M        1 
VM_ALLOCATE                        156K        8 
VM_ALLOCATE (reserved)             384K        3         reserved VM address space (unallocated)
__CTF                               824        1 
__DATA                            14.0M      482 
__DATA_CONST                      57.3M      504 
__DATA_DIRTY                      1117K      152 
__FONT_DATA                        2352        1 
__LINKEDIT                       169.2M        2 
__OBJC_RO                         61.3M        1 
__OBJC_RW                         2395K        2 
__TEXT                           684.0M      518 
__TPRO_CONST                         16        2 
mapped file                       60.4M       11 
shared memory                      792K       17 
===========                     =======  ======= 
TOTAL                              1.7G     1840 
TOTAL, minus reserved VM space     1.7G     1840 



-----------
Full Report
-----------

{"app_name":"芒果云创作","timestamp":"2025-08-13 16:56:11.00 +0800","app_version":"1.3.2","slice_uuid":"eab44a5d-35bf-3f8c-a7b9-d7353ffce081","build_version":"1.3.2","platform":1,"bundleID":"com.mango.cloud","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 15.5 (24F74)","roots_installed":0,"name":"芒果云创作","incident_id":"BECDD068-86E0-4B01-B0C8-2494A4612E0E"}
{
  "uptime" : 21000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro16,1",
  "coalitionID" : 5146,
  "osVersion" : {
    "train" : "macOS 15.5",
    "build" : "24F74",
    "releaseType" : "User"
  },
  "captureTime" : "2025-08-13 16:56:11.1942 +0800",
  "codeSigningMonitor" : 0,
  "incident" : "BECDD068-86E0-4B01-B0C8-2494A4612E0E",
  "pid" : 13369,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2025-08-13 16:56:11.0622 +0800",
  "procStartAbsTime" : 21953190173077,
  "procExitAbsTime" : 21953321541048,
  "procName" : "芒果云创作",
  "procPath" : "\/Applications\/芒果云创作.app\/Contents\/MacOS\/芒果云创作",
  "bundleInfo" : {"CFBundleShortVersionString":"1.3.2","CFBundleVersion":"1.3.2","CFBundleIdentifier":"com.mango.cloud"},
  "storeInfo" : {"deviceIdentifierForVendor":"276267CD-5F90-56F4-9F66-962ED0CC7F0E","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.mango.cloud",
  "crashReporterKey" : "D4684E1C-A2C6-A2BC-CC24-F46D4F94A9DE",
  "appleIntelligenceStatus" : {"state":"unavailable","reasons":["deviceNotCapable"]},
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 4294967295,
  "codeSigningAuxiliaryInfo" : 0,
  "bootSessionUUID" : "74CF405D-3C4D-49DF-84DF-21E56F3B82CC",
  "wakeTime" : 12284,
  "bridgeVersion" : {"build":"22P5072","train":"9.5"},
  "sleepWakeUUID" : "9128DF30-E704-48BD-B65A-2C9924E5882E",
  "sip" : "enabled",
  "vmRegionInfo" : "0 is not in any region.  Bytes before following region: 4355964928\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      103a2c000-1076a2000    [ 60.5M] r-x\/r-x SM=COW  \/Applications\/芒果云创作.app\/Contents\/MacOS\/芒果云创作",
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000000"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":13369},
  "vmregioninfo" : "0 is not in any region.  Bytes before following region: 4355964928\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      103a2c000-1076a2000    [ 60.5M] r-x\/r-x SM=COW  \/Applications\/芒果云创作.app\/Contents\/MacOS\/芒果云创作",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"queue":"com.apple.main-thread","instructionState":{"instructionStream":{"bytes":[44,131,199,184,139,21,250,206,166,65,57,215,125,49,137,250,193,250,6,72,99,210,72,141,53,231,205,166,65,72,139,148,214,128,0,0,0,72,133,210,116,21,131,231,63,72,141,20,250,72,139,18,72,57,209,117,8,49,192,15,182,192,195,49,210,246,193,1,116,245,72,139,5,199,198,252,61,72,35,8,72,57,209,15,149,192,235,227,176,1,64,246,198,1,117,110,72,139,14,72,133,201,116,30,72,131,255,7,117,9,72,59,13,143,118,134,65,116,85,72,131,255,71,119,23,72,141,21,136,206,166,65,235,58,72,133,255,116,65,85,72,137,229,232,107,50,9,0,131,199,184,139,21,103,206,166,65,57,215,125,49,137,250,193,250,6,72,99,210,72,141,53,84,205,166,65,72,139,148,214,128,0,0,0,72,133,210,116,21,131,231,63],"offset":96}},"frames":[{"imageOffset":1337892,"symbol":"CF_IS_OBJC","symbolLocation":8,"imageIndex":1},{"imageOffset":28486,"symbol":"CFStringGetLength","symbolLocation":60,"imageIndex":1},{"imageOffset":40758,"symbol":"CFStringFindWithOptionsAndLocale","symbolLocation":76,"imageIndex":1},{"imageOffset":40658,"symbol":"CFStringHasPrefix","symbolLocation":55,"imageIndex":1},{"imageOffset":1084824,"symbol":"__CFBundleCopyFrameworkURLForExecutablePath","symbolLocation":456,"imageIndex":1},{"imageOffset":422540,"symbol":"_CFBundleEnsureBundleExistsForImagePath","symbolLocation":19,"imageIndex":1},{"imageOffset":1159540,"symbol":"_CFBundleGetBundleWithIdentifier","symbolLocation":194,"imageIndex":1},{"imageOffset":47782,"symbol":"+[NSBundle bundleWithIdentifier:]","symbolLocation":27,"imageIndex":2},{"imageOffset":16163818,"symbol":"objc2_foundation::generated::__NSBundle::NSBundle::bundleWithIdentifier::h253b1ed1e050c806","symbolLocation":42,"imageIndex":0},{"imageOffset":15721984,"symbol":"wry::wkwebview::platform_webview_version::hb9b91d811afe6d6d","symbolLocation":48,"imageIndex":0},{"imageOffset":15762910,"symbol":"wry::webview_version::hde2cb6b03a0583bf","symbolLocation":14,"imageIndex":0},{"imageOffset":5886253,"symbol":"_$LT$tauri_runtime_wry..Wry$LT$T$GT$$u20$as$u20$tauri_runtime..Runtime$LT$T$GT$$GT$::new::h2531c2391a7d348c","symbolLocation":1421,"imageIndex":0},{"imageOffset":3358569,"symbol":"tauri::app::Builder$LT$R$GT$::run::h0e308aebf171b4a2","symbolLocation":937,"imageIndex":0},{"imageOffset":7519018,"symbol":"mango_cloud_app_lib::main::h0eb9c1213bdd2d20","symbolLocation":2938,"imageIndex":0},{"imageOffset":4182,"symbol":"std::sys::backtrace::__rust_begin_short_backtrace::haf7f69fd950d2fba","symbolLocation":6,"imageIndex":0},{"imageOffset":4172,"symbol":"std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h35d844152020e1a5","symbolLocation":12,"imageIndex":0},{"imageOffset":21817774,"symbol":"std::rt::lang_start_internal::ha4af94bb3c6aded2","symbolLocation":814,"imageIndex":0},{"imageOffset":4268,"symbol":"main","symbolLocation":44,"imageIndex":0},{"imageOffset":25904,"symbol":"start","symbolLocation":3056,"imageIndex":3}],"id":407404,"triggered":true,"threadState":{"r13":{"value":140701992798832},"rax":{"value":2304939121002151937},"rflags":{"value":66118},"cpu":{"value":0},"r14":{"value":105553149952528},"rsi":{"value":0},"r8":{"value":8},"cr2":{"value":0},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":0},"r15":{"value":8},"rbx":{"value":0},"trap":{"value":14,"description":"(no mapping for user data read)"},"err":{"value":4},"r11":{"value":140703220844800,"symbolLocation":0,"symbol":"trailingBytesForUTF8"},"rip":{"value":140703219968548,"matchesCrashFrame":1},"rbp":{"value":140701992795120},"rsp":{"value":140701992795096},"r12":{"value":8},"rcx":{"value":8},"flavor":"x86_THREAD_STATE","rdi":{"value":7}},"name":"main"},{"id":407422,"name":"r2d2-worker-0","threadState":{"r13":{"value":1103806595584},"rax":{"value":260},"rflags":{"value":583},"cpu":{"value":0},"r14":{"value":140411733576488},"rsi":{"value":1103806595584},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":256},"r10":{"value":0},"r9":{"value":160},"r15":{"value":256},"rbx":{"value":123145411293184},"trap":{"value":133},"err":{"value":33554737},"r11":{"value":582},"rip":{"value":140703217923830},"rbp":{"value":123145411291712},"rsp":{"value":123145411291560},"r12":{"value":123145411291584},"rcx":{"value":123145411291560},"flavor":"x86_THREAD_STATE","rdi":{"value":140411733576488}},"frames":[{"imageOffset":14070,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":5},{"imageOffset":25210,"symbol":"_pthread_cond_wait","symbolLocation":988,"imageIndex":6},{"imageOffset":17854474,"symbol":"parking_lot::condvar::Condvar::wait_until_internal::hdf942318cf576c96","symbolLocation":682,"imageIndex":0},{"imageOffset":17839775,"symbol":"scheduled_thread_pool::Worker::run::h32379fadda013a63","symbolLocation":111,"imageIndex":0},{"imageOffset":17842291,"symbol":"std::sys::backtrace::__rust_begin_short_backtrace::hc8c0664ec5cb5a10","symbolLocation":19,"imageIndex":0},{"imageOffset":17847987,"symbol":"core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h5f83fbf7ddcd8680","symbolLocation":179,"imageIndex":0},{"imageOffset":21884331,"symbol":"std::sys::pal::unix::thread::Thread::new::thread_start::h7feb70d0ed1fab2c","symbolLocation":43,"imageIndex":0},{"imageOffset":24049,"symbol":"_pthread_start","symbolLocation":99,"imageIndex":6},{"imageOffset":6231,"symbol":"thread_start","symbolLocation":15,"imageIndex":6}]},{"id":407423,"name":"r2d2-worker-1","threadState":{"r13":{"value":1103806595584},"rax":{"value":260},"rflags":{"value":583},"cpu":{"value":0},"r14":{"value":140411741971240},"rsi":{"value":1103806595584},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":256},"r10":{"value":0},"r9":{"value":160},"r15":{"value":256},"rbx":{"value":123145413402624},"trap":{"value":133},"err":{"value":33554737},"r11":{"value":582},"rip":{"value":140703217923830},"rbp":{"value":123145413401152},"rsp":{"value":123145413401000},"r12":{"value":123145413401024},"rcx":{"value":123145413401000},"flavor":"x86_THREAD_STATE","rdi":{"value":140411741971240}},"frames":[{"imageOffset":14070,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":5},{"imageOffset":25210,"symbol":"_pthread_cond_wait","symbolLocation":988,"imageIndex":6},{"imageOffset":17854474,"symbol":"parking_lot::condvar::Condvar::wait_until_internal::hdf942318cf576c96","symbolLocation":682,"imageIndex":0},{"imageOffset":17839775,"symbol":"scheduled_thread_pool::Worker::run::h32379fadda013a63","symbolLocation":111,"imageIndex":0},{"imageOffset":17842291,"symbol":"std::sys::backtrace::__rust_begin_short_backtrace::hc8c0664ec5cb5a10","symbolLocation":19,"imageIndex":0},{"imageOffset":17847987,"symbol":"core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h5f83fbf7ddcd8680","symbolLocation":179,"imageIndex":0},{"imageOffset":21884331,"symbol":"std::sys::pal::unix::thread::Thread::new::thread_start::h7feb70d0ed1fab2c","symbolLocation":43,"imageIndex":0},{"imageOffset":24049,"symbol":"_pthread_start","symbolLocation":99,"imageIndex":6},{"imageOffset":6231,"symbol":"thread_start","symbolLocation":15,"imageIndex":6}]},{"id":407424,"name":"r2d2-worker-2","threadState":{"r13":{"value":4294967552},"rax":{"value":260},"rflags":{"value":583},"cpu":{"value":0},"r14":{"value":140411716797736},"rsi":{"value":4294967552},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":160},"r15":{"value":0},"rbx":{"value":123145415512064},"trap":{"value":133},"err":{"value":33554737},"r11":{"value":582},"rip":{"value":140703217923830},"rbp":{"value":123145415510592},"rsp":{"value":123145415510440},"r12":{"value":123145415510464},"rcx":{"value":123145415510440},"flavor":"x86_THREAD_STATE","rdi":{"value":140411716797736}},"frames":[{"imageOffset":14070,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":5},{"imageOffset":25210,"symbol":"_pthread_cond_wait","symbolLocation":988,"imageIndex":6},{"imageOffset":17854474,"symbol":"parking_lot::condvar::Condvar::wait_until_internal::hdf942318cf576c96","symbolLocation":682,"imageIndex":0},{"imageOffset":17839775,"symbol":"scheduled_thread_pool::Worker::run::h32379fadda013a63","symbolLocation":111,"imageIndex":0},{"imageOffset":17842291,"symbol":"std::sys::backtrace::__rust_begin_short_backtrace::hc8c0664ec5cb5a10","symbolLocation":19,"imageIndex":0},{"imageOffset":17847987,"symbol":"core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h5f83fbf7ddcd8680","symbolLocation":179,"imageIndex":0},{"imageOffset":21884331,"symbol":"std::sys::pal::unix::thread::Thread::new::thread_start::h7feb70d0ed1fab2c","symbolLocation":43,"imageIndex":0},{"imageOffset":24049,"symbol":"_pthread_start","symbolLocation":99,"imageIndex":6},{"imageOffset":6231,"symbol":"thread_start","symbolLocation":15,"imageIndex":6}]},{"id":407432,"frames":[{"imageOffset":6196,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":9475},"r8":{"value":409604},"cr2":{"value":0},"rdx":{"value":123145415524352},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":123145416047480},"rbx":{"value":123145416048640},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703218165812},"rbp":{"value":0},"rsp":{"value":123145416048640},"r12":{"value":5193734},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145416048640}}},{"id":407433,"frames":[{"imageOffset":6196,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":11011},"r8":{"value":409602},"cr2":{"value":0},"rdx":{"value":123145416060928},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":123145416584056},"rbx":{"value":123145416585216},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703218165812},"rbp":{"value":0},"rsp":{"value":123145416585216},"r12":{"value":5193730},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145416585216}}},{"id":407436,"frames":[{"imageOffset":6196,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":20999},"r8":{"value":5193730},"cr2":{"value":0},"rdx":{"value":123145416597504},"r10":{"value":0},"r9":{"value":1},"r15":{"value":123145417120632},"rbx":{"value":123145417121792},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703218165812},"rbp":{"value":0},"rsp":{"value":123145417120624},"r12":{"value":5193734},"rcx":{"value":123145417120640},"flavor":"x86_THREAD_STATE","rdi":{"value":123145417121792}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4355964928,
    "CFBundleShortVersionString" : "1.3.2",
    "CFBundleIdentifier" : "com.mango.cloud",
    "size" : 63397888,
    "uuid" : "eab44a5d-35bf-3f8c-a7b9-d7353ffce081",
    "path" : "\/Applications\/芒果云创作.app\/Contents\/MacOS\/芒果云创作",
    "name" : "芒果云创作",
    "CFBundleVersion" : "1.3.2"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703218630656,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 4935667,
    "uuid" : "2f3a4185-6038-37d0-a02b-ec620bcd977b",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "3502.1.401"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703236853760,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 14620850,
    "uuid" : "3e72de1d-c81a-3c8b-9c06-5b1e3186de47",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "3502.1.401"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703214333952,
    "size" : 632104,
    "uuid" : "3771ea6a-0fe5-3b63-961d-c09e01d5e680",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703217909760,
    "size" : 248656,
    "uuid" : "dab10aa4-8afa-3d02-9cde-6023554ac858",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703218159616,
    "size" : 48592,
    "uuid" : "a6d1f05a-0743-31b7-9fe2-268f06ccd51a",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 140703185891328,
  "size" : 30064771072,
  "uuid" : "57b0c2b8-36d6-3cf0-8bd0-0ac6133ec8b3"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=853.2M resident=0K(0%) swapped_out_or_unallocated=853.2M(100%)\nWritable regions: Total=652.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=652.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                          160K       23 \nCoreServices                       236K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           635.7M       84 \nMALLOC guard page                   48K       12 \nSTACK GUARD                         24K        6 \nStack                             15.5M        7 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                        156K        8 \nVM_ALLOCATE (reserved)             384K        3         reserved VM address space (unallocated)\n__CTF                               824        1 \n__DATA                            14.0M      482 \n__DATA_CONST                      57.3M      504 \n__DATA_DIRTY                      1117K      152 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       169.2M        2 \n__OBJC_RO                         61.3M        1 \n__OBJC_RW                         2395K        2 \n__TEXT                           684.0M      518 \n__TPRO_CONST                         16        2 \nmapped file                       60.4M       11 \nshared memory                      792K       17 \n===========                     =======  ======= \nTOTAL                              1.7G     1840 \nTOTAL, minus reserved VM space     1.7G     1840 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "name" : "main",
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "ae5e71ad0948fe860e3c368ee1f50d6d1ffa8e26",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "645eb1d0417dab722a215927",
      "factorPackIds" : {

      },
      "deploymentId" : 240000005
    },
    {
      "rolloutId" : "5f72dc58705eff005a46b3a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    }
  ],
  "experiments" : [

  ]
}
}
```

**Comment by haecker-felix** [comment]
Same crash here. 

```
thread 'main' panicked at /Users/haecker-felix/Library/Caches/rattler/cache/bld/work/pixi-wNHU1yfeWtQ/bld/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wry-0.53.2/src/wkwebview/mod.rs:1263:90:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: wry::wkwebview::platform_webview_version
   5: <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::new
   6: pixi_lib::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

In my case, I am trying to package a Tauri app in an isolated [Pixi](https://pixi.sh/latest/#quick-demo) environment. It appears that accessing the `com.apple.WebKit` bundle from such an environment is not possible.

The actual `.unwrap()` which fails here is (`wry` crate): 

```rust
NSBundle::bundleWithIdentifier(&NSString::from_str("com.apple.WebKit")).unwrap(); // <- panic!
```

The code which triggers that crash  is in the `init()` function (`tauri-runtime-wry` crate):
https://github.com/tauri-apps/tauri/blob/dev/crates/tauri-runtime-wry/src/lib.rs#L2782

Which got introduced with https://github.com/tauri-apps/tauri/pull/13406.

As a workaround, downgrade Tauri to 2.5.1 which doesn't include `wry::webview_version().is_ok()` in the `init()` function (but the actual app opens perfectly fine then! - at least in my case).

**Comment by lucasfernog** [comment]
> Same crash here.
> 
> ```
> thread 'main' panicked at /Users/haecker-felix/Library/Caches/rattler/cache/bld/work/pixi-wNHU1yfeWtQ/bld/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wry-0.53.2/src/wkwebview/mod.rs:1263:90:
> called `Option::unwrap()` on a `None` value
> stack backtrace:
>    0: __rustc::rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::panicking::panic
>    3: core::option::unwrap_failed
>    4: wry::wkwebview::platform_webview_version
>    5: <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::new
>    6: pixi_lib::run
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ```
> 
> In my case, I am trying to package a Tauri app in an isolated [Pixi](https://pixi.sh/latest/#quick-demo) environment. It appears that accessing the `com.apple.WebKit` bundle from such an environment is not possible.
> 
> The actual `.unwrap()` which fails here is (`wry` crate):
> 
> NSBundle::bundleWithIdentifier(&NSString::from_str("com.apple.WebKit")).unwrap(); // <- panic!
> The code which triggers that crash is in the `init()` function (`tauri-runtime-wry` crate): https://github.com/tauri-apps/tauri/blob/dev/crates/tauri-runtime-wry/src/lib.rs#L2782
> 
> Which got introduced with [#13406](https://github.com/tauri-apps/tauri/pull/13406).
> 
> As a workaround, downgrade Tauri to 2.5.1 which doesn't include `wry::webview_version().is_ok()` in the `init()` function (but the actual app opens perfectly fine then! - at least in my case).

this particular crash was fixed [here](https://github.com/tauri-apps/wry/pull/1609) it'll be published to wry 0.53.3

**Comment by handexing** [comment]
@lucasfernog 
I see that the WRY referenced in the project is already version 0.53.3, but it still crashes with errors

> 
Thread 0 Crashed:: main Dispatch queue: com.apple.main-thread
0   CoreFoundation                	    0x7ff8136c38c4 CF_IS_OBJC + 8
1   CoreFoundation                	    0x7ff813583df6 CFStringGetLength + 60
2   CoreFoundation                	    0x7ff813586de6 CFStringFindWithOptionsAndLocale + 76
3   CoreFoundation                	    0x7ff813586d82 CFStringHasPrefix + 55
4   CoreFoundation                	    0x7ff813685c38 __CFBundleCopyFrameworkURLForExecutablePath + 456
5   CoreFoundation                	    0x7ff8135e413c _CFBundleEnsureBundleExistsForImagePath + 19
6   CoreFoundation                	    0x7ff813698014 _CFBundleGetBundleWithIdentifier + 194
7   Foundation                    	    0x7ff8146eaaa6 +[NSBundle bundleWithIdentifier:] + 27
8   芒果云创作                         	       0x10770d05a objc2_foundation::generated::__NSBundle::NSBundle::bundleWithIdentifier::hfe0a5630b27fa015 + 42
9   芒果云创作                         	       0x107620d90 wry::wkwebview::platform_webview_version::h1a80560f3a99cd03 + 48
10  芒果云创作                         	       0x107631d2e wry::webview_version::ha7382d9e03ca6aa5 + 14
11  芒果云创作                         	       0x106b0c2a3 _$LT$tauri_runtime_wry..Wry$LT$T$GT$$u20$as$u20$tauri_runtime..Runtime$LT$T$GT$$GT$::new::h44314ba06bf24487 + 1411
12  芒果云创作                         	       0x106e2ec85 tauri::app::Builder$LT$R$GT$::run::h7c0f83216fd5566c + 981
13  芒果云创作                         	       0x106b8e784 mango_cloud_app_lib::main::h660346cd67dc297a + 2276
14  芒果云创作                         	       0x106689196 std::sys::backtrace::__rust_begin_short_backtrace::h3befcd1ab5284645 + 6
15  芒果云创作                         	       0x10668918c std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h4c257f8889f80741 + 12
16  芒果云创作                         	       0x107c413e5 std::rt::lang_start_internal::hebe6f07820d85ef8 + 917
17  芒果云创作                         	       0x1066891ec main + 44
18  dyld                          	    0x7ff81316a530 start + 3056

**Comment by haecker-felix** [comment]
I can confirm that tauri doesn't crash anymore, but the webview doesn't get initialized (=no visible window), which makes sense, given the webview only gets created when `webview_runtime_installed` is `true` (which isn't the case - at least for me). 

https://github.com/tauri-apps/tauri/blob/f70b28529d226a2dec2f41709d8934f8f5adab25/crates/tauri-runtime-wry/src/lib.rs#L4523

I tested with the `webview_runtime_installed` check removed, the webview window gets created perfectly fine. So maybe Tauri could try to create a webview anyway, despite `webview_runtime_installed` being `false`?

**Comment by Hofer-Julian** [comment]
> I tested with the webview_runtime_installed check removed, the webview window gets created perfectly fine. So maybe Tauri could try to create a webview anyway, despite webview_runtime_installed being false?

It would also been nice if the reason why this check failed would be logged

**Comment by handexing** [comment]
I have created a new project and copied all the code to make it normal
