### ISSUE TITLE
Building installer on Windows with wix options specified failed for the first ever call

### ISSUE THREAD

**Issue by kimlimjustin** [tauri-apps/tauri#2927]
### **Describe the bug**
Building installer on Windows with Wix options (license, template) specified failed if the user never called the build before.

### **To Reproduce**
1. Run `yarn create tauri-app`.
2. Select the vanilla template and leave everything simple
3. Open the tauri-app generated
4. Create a `LICENSE` file
5. Link that `LICENSE` file by adding `license` key into `tauri.bundle.windows.wix` of `src-tauri/tauri.conf.json` with the value of `../LICENSE`
6. Run build
7. See the error

Now to fix that:
1. Remove the `license` section
2. Run build
3. Add back the `license` section
4. Now it's ok

### **Expected behavior**
It works fine even on the first call, cuz when calling the build via workflow, it will all fail (unless trick it by running prebuild and postbuild)

### **Screenshots**
Code Structure:
![image](https://user-images.githubusercontent.com/61906684/142599560-5f9a09d0-8a89-4b90-a2b7-39eeef9ece78.png)

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.22000 X64
Webview2 - 95.0.1020.53

Node.js environment
  Node.js - 16.0.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 7.10.0
  yarn - 1.22.11

Rust environment
  rustc - 1.56.0
  cargo - 1.56.0

App directory structure
/dist
/node_modules
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - ../dist
build-type
CSP
```

**Comment by amrbashir** [comment]
Opened a PR at #2987 that should fix this. Please next time include the error, it would've saved me some time.

**Comment by kimlimjustin** [comment]
Not sure if I tested it correctly, but it still does not work.
```toml
tauri = { git="https://github.com/tauri-apps/tauri", branch="feat/active-toolchain", features = ["api-all"] }
```
![image](https://user-images.githubusercontent.com/61906684/144061342-08754ce4-3731-4ae2-a29e-6572b6dcf934.png)

> Please next time include the error, it would've saved me some time.

Really sorry but I thought the error message is not something significant because it's not that informative (for me) and I didn't even understand what it's saying about

**Comment by amrbashir** [comment]
@kimlimjustin Oh sorry I linked the wrong PR (updated the comment)>

To test this you need to build the `cli.rs` crate not the `tauri` crate. try `cargo install tauri-cli --git https://github.com/tauri-apps/tauri --branch fix/wix-license` .

**Comment by kimlimjustin** [comment]
I don't think it's fixed tho...
https://github.com/kimlimjustin/xplorer/runs/4595183538?check_suite_focus=true

**Comment by FabianLars** [comment]
> I don't think it's fixed tho...

Like amr said, you need to use the git version of the rust based cli. That workflow run used the npm package, which will use the last **released** version of cli.rs
