### ISSUE TITLE
[bug] Black screen and unresponsive buttons on Windows after minimizing a maximizing frameless window

### ISSUE THREAD

**Issue by adaptive-simon** [tauri-apps/tauri#3498]
### Describe the bug

When you have a frameless window with custom titlebar buttons and you maximize, minimize, then maximize again, the entire window sometimes just goes black. Sometimes the window won't be black, but the buttons no longer function. In the cases where the window isn't black the window remains responsive to system commands that control the window, such as clicking the application icon in the taskbar in order to minimize it. The behavior seems to be more stable when using `toggleMaximize()` rather than just `maximize()` and `minimize()`.

Minimizing the window while not in maximized mode by clicking the application icon in the taskbar appears to fix the button as long as you're not in maximized mode.

As long as you don't enter maximized mode the behavior is stable, it's only when you've entered maximized mode that bugs start appearing.

### Reproduction

1. Create a new project
2. Set `"decorations": "false"` in `tauri.conf.json`
3. Create buttons that run `appWindow.toggleMaximize()` and `appWindow.minimize()`
4. Maximize the window
5. Minimize the window
6. Open the window again
7. The minimize and/or maximize buttons now don't work, and sometimes the window is black

### Expected behavior

The window was supposed to be maximized, minimized, then opened again, without buttons seizing to function or the window being black.

### Platform and versions

```shell
Operating System - Windows, version 10.0.22000 X64
Webview2 - 98.0.1108.50
Visual Studio Build Tools:
   - Visual Studio Community 2019
   - Visual Studio Build Tools 2017
   - Visual Studio Community 2017

Node.js environment
  Node.js - 14.17.4
  @tauri-apps/cli - 1.0.0-rc.4
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 7.22.0
  pnpm - Not installed
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.git
/.github
/.idea
/.nuxt
/node_modules
/src
/src-tauri
/target

App
  tauri - 1.0.0-rc.2 (no lockfile)
  tauri-build - no manifest (no lockfile)
  tao - no manifest (no lockfile)
  wry - no manifest (no lockfile)
  build-type - bundle
  CSP - unset
  distDir - ../public
  devPath - http://127.0.0.1:32146/
  framework - Vue.js (Nuxt)
  bundler - Webpack
```

### Additional context

I believe the issue is related to e.g. booleans being in the improper state, e.g. that using `maximize()` sets an internal value to keep track of its state, rather than fetching the actual state every time from the system. I have absolutely no idea why the maximized state of the application would influence the ability to minimize the window. So far I've only had these issues when using custom buttons with a frameless window, using a normal decorated window has thus far been problem free.

The black window issue only happens sometimes when I try the procedure on one of my monitors, on the other it never happens. On both monitors the buttons no longer functioning occurs. By exiting maximized mode and using system commands to minimize and unminimize the window it would appear that the buttons start to work again, until you break then again.

**Comment by Silbad** [comment]
Hello, same pb win11

**Comment by amrbashir** [comment]
Can you guys record this behavior? While investigating this, I encountered a bug where custom minimize button doesn't minimize the window correctly if it is maximized but I never got that black screen.

**Comment by Silbad** [comment]
I updated to the latest version and indeed I have the same problem as you with custom minimize button. We can reproduce the black screen bug with the button to minimize, but as this one does not work anymore...

**Comment by Silbad** [comment]
This may not be the page to talk about it but is it possible to reproduce the win11 hover?
![image](https://user-images.githubusercontent.com/31576982/156184150-06927027-a10c-4a6b-9e2d-b2af440dc94e.png)

**Comment by amrbashir** [comment]
@Silbad this minimize bug I talked about is fixed in tauri-apps/tao#334 and will be available in the next release. 

I can't reproduce The black screen bug however so I will close this issue now. And let me know if it happens on the next release.

**Comment by amrbashir** [comment]
> This may not be the page to talk about it but is it possible to reproduce the win11 hover? ![image](https://user-images.githubusercontent.com/31576982/156184150-06927027-a10c-4a6b-9e2d-b2af440dc94e.png)

This doesn't work when `decorations` is disabled which is intended because it is hard to know the location of the custom maximize button. I think I have a way to achieve this, similar to `data-tauri-drag-region` but It will have to wait until tauri v2.

**Comment by Silbad** [comment]
Thanks, ok I wait for the next release ;)

**Comment by amrbashir** [comment]
tao hasn't been published yet which includes the fix for the bug. I will see if it can be published today. For now you can try the fix by adding this inside your Cargo.toml
```toml
[patch.crates-io]
tao = { git = "https://github.com/tauri-apps/tao", rev = "475e64d2873c233e60cb74e52e91282d18e13780" }
```

**Comment by amrbashir** [comment]
@Silbad it is now published, run `cargo update -p tao` inside `src-tauri`

**Comment by Silbad** [comment]
oh... (-_-) ok :)

**Comment by Silbad** [comment]
Ok I update to tao v0.6.4, and I find the initial bug with the black screen (win11) : 

- launch dev mod
- maximize : not ok => a flash and the window returns to its initial state
- re-maximize : ok
- minimize : ok
- clic on the icon in the taskbar to maximize : not ok => black screen. The famous.

**Comment by amrbashir** [comment]
@Silbad I can't reproduce this at all and I am on win11. Try creating a minimal repro and post it here and if the bug happens, try to record it.

**Comment by Silbad** [comment]
Okay I'll do that for you. What is the best application to record the Win11 desktop? I tried win+g but it doesn't work with tauri app...

**Comment by amrbashir** [comment]
use [ScreenToGif](https://www.screentogif.com)

**Comment by Silbad** [comment]
![tauri_black_screen](https://user-images.githubusercontent.com/31576982/157823686-a99d2c6e-ed06-4c5a-aa2b-aa78a246aead.gif)

**Comment by Silbad** [comment]
I update the process https://github.com/tauri-apps/tauri/issues/3498#issuecomment-1061234686

**Comment by adaptive-simon** [comment]
For me setting `1.0.0-rc.4` in Cargo.toml and running `cargo update` has resolved the issue. The only problem that remains seems to be that `toggleMaximize()` only maximizes but never minimizes as would be expected from a function called "toggle".

So my solution for that problem was simply doing it "manually":
```javascript
async maximize() {
  if (await appWindow.isMaximized()) {
    appWindow.unmaximize()
  } else {
    appWindow.maximize()
  }
}
```

**Comment by arkhon7** [comment]
The `minimize()` seems also to be a problem. It does work when you don't maximize the window, but after maximizing it, the subsequent minimize events will not work.  ```js
// this condition is valid when pressing minimize
        if (await appWindow.isMaximized()) { 
            
            console.log('minimized the maximized window!')
            appWindow.minimize() // the program minimizes for like 1 frame

            // then goes back into maximized again
            // after then the condition is still valid on subsequent press events but won't minimize.

        } else {
            console.log('minimized the normal window!')
            appWindow.minimize()
        }
```

**Comment by amrbashir** [comment]
@arkhon7 this should be fixed now, make sure to use latest version

**Comment by adaptive-simon** [comment]
> > only maximizes but never minimizes
> 
> minimize is not the opposite of maximize, but judging from your code snippet that may just be misphrased i guess?
> 
> And about that snippet, that's actually the same toggleMaximize does behind the scenes. On that note, toggleMaximize seems to work as intended on my end (and if i understood the messages here correctly, then it does for the others too). Edit: "intended" as in, it calls either maximize or unmaximize (so it never _minimizes_), just to be 100% clear.

Yea sorry just misphrased, you undestood me correctly.

Also I discovered that the black screen still sometimes happens, but only on one monitor for some reason. Seems more stable now at least, I'm no longer afraid of my window control buttons haha.

**Comment by Silbad** [comment]
> @arkhon7 this should be fixed now, make sure to use latest version

I update cargo, the issue still here :(

**Comment by amrbashir** [comment]
The minimize issue is fixed in the latest tauri release. It has nothing to do with cargo or rust version.

**Comment by Silbad** [comment]
I update cli and api too (https://tauri.studio/docs/development/updating-dependencies), issue still here, sorry

**Comment by amrbashir** [comment]
The issue described in this comment https://github.com/tauri-apps/tauri/issues/3498#issuecomment-1070848736 is fixed, the black screen is not as I am not able to reproduce it nor I have a clue what might cause it.

**Comment by Silbad** [comment]
Ok I understand...

**Comment by Silbad** [comment]
![Wye9oPn](https://user-images.githubusercontent.com/31576982/161371500-4f2bdf5e-51df-479d-9d1e-2c7eaf5a75d3.png)

ok I have a new clue, then I'll stop bothering you with it. I have three screens, it works on screen 2, and I reproduce the bug on screens 1 and 3. So actually not a code problem I think.

**Comment by Sheap** [comment]
FWIW, I also have the black screen issue. Similarly to @Silbad I have 2 monitors, the issue occurs reliably on my right monitor, but on the left most monitor, everything works fine.

**Comment by Silbad** [comment]
> FWIW, I also have the black screen issue. Similarly to @Silbad I have 2 monitors, the issue occurs reliably on my right monitor, but on the left most monitor, everything works fine.

I'm not alone 🙏

**Comment by idlist** [comment]
Also got this problem with exactly the same procedures. I have two screens and set the left one as the 2nd screen and the right one as the 1st screen. The issue could be reproduced in my 1st screen as it is not the leftmost screen 🤔

**Comment by FuelKubitox** [comment]
I have the same issue. Got 2 monitors and on the left everything is fine, but on my primary screen i have the bug.

**Comment by agersant** [comment]
I can reproduce this issue with 100% success on a fresh project. Here is a video showing the full setup (the secondary monitor is displayed in the bottom right corner as Picture-In-Picture). 

https://user-images.githubusercontent.com/817256/170193070-4fdea4cb-3270-4b4d-a674-139f82516faf.mp4

The steps are:
- Follow the Getting Started guide on `tauri.studio` to create a new project (I used Vanilla.js to minimize moving parts but I originally ran into this in a Vue application).
- Follow the `Window Customization` guide on `tauri.studio`
- Run the application via `cargo tauri dev`
- Drag the application to secondary monitor
- Maximize the application through any means (`appWindow` JS API, using Windows Key + arrow keys, etc.)
- Minimize the application through any means (`appWindow` JS API, task bar button, etc.)
- Click the task bar button to maximize the window again
- Observe black screen

`tauri info` output:
```
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 101.0.1210.53
  › MSVC:
      - Visual Studio Build Tools 2019
  › Node.js: 14.16.0
  › npm: 6.14.11
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.11(outdated, latest: 1.0.0-rc.12)
  › @tauri-apps/api [NPM]: 1.0.0-rc.6
  › tauri [RUST]: 1.0.0-rc.12,
  › tauri-build [RUST]: 1.0.0-rc.10,
  › tao [RUST]: 0.9.1,
  › wry [RUST]: 0.17.0,

App
  › build-type: bundle 
  › CSP: unset
  › distDir: ../dist   
  › devPath: ../dist   

App directory structure
  ├─ dist
  ├─ node_modules      
  └─ src-tauri
```

**Comment by w-henderson** [comment]
I'm having the same issue when minimizing on my primary monitor of my two monitors - I think this should be a priority since several users are reporting this bug to me in my application.

**Comment by lucasfernog** [comment]
@amrbashir can you check this one?

**Comment by amrbashir** [comment]
I can't investigate this probably since I don't have a multi-monitor setup but I made two attempts and I need you guys to test them and post the logs from each one.

[notify_parent_window_pos_changed.zip](https://github.com/tauri-apps/tauri/files/8948361/notify_parent_window_pos_changed.zip)
[resize_on_moved.zip](https://github.com/tauri-apps/tauri/files/8948362/resize_on_moved.zip)

**Comment by adaptive-simon** [comment]
@amrbashir Your attempts don't use an undecorated window. The bug only happens on undecorated windows

**Comment by amrbashir** [comment]
Oh my bad, here is one with undecorated windows

[resize_on_moved.zip](https://github.com/tauri-apps/tauri/files/8948706/resize_on_moved.zip)
[notify_parent_window_pos_changed_on_moved.zip](https://github.com/tauri-apps/tauri/files/8948704/notify_parent_window_pos_changed_on_moved.zip)

**Comment by FabianLars** [comment]
[notify_parent.txt](https://github.com/tauri-apps/tauri/files/8948891/notify_parent.txt)
[resize_on_moved.txt](https://github.com/tauri-apps/tauri/files/8948892/resize_on_moved.txt)

**Comment by adaptive-simon** [comment]
resize_on_moved:
![image](https://user-images.githubusercontent.com/79983560/174800637-69eace93-3c76-4581-a99d-787a9581f0fb.png)

notify_parent:
![image](https://user-images.githubusercontent.com/79983560/174800861-df10c954-e1bb-425a-9e42-c21cbc576d28.png)

**Comment by adaptive-simon** [comment]
@amrbashir  That's the complete output from the test, there's nothing more above or below. So yea that might be a hint as to what the bug is 🙂 

notify_parent:
![image](https://user-images.githubusercontent.com/79983560/174803466-616008f9-9d5c-4a0b-b60c-2d1e6306dd0f.png)

resize_on_moved:
![image](https://user-images.githubusercontent.com/79983560/174803811-335807c1-0e40-4f5d-a419-9811134a8833.png)

**Comment by amrbashir** [comment]
opened an upstream issue at https://github.com/MicrosoftEdge/WebView2Feedback/issues/2549
