### ISSUE TITLE
[bug] Notification API Error: thread 'main' panicked at 'This API cannot be called on the main thread

### ISSUE THREAD

**Issue by zhanglun** [tauri-apps/tauri#3696]
### Describe the bug

There is a button on the page that calls the Notification API after the button is clicked.
When I click the button, app crashed, terminal message shows like

```bash
thread 'main' panicked at 'This API cannot be called on the main thread. Try using `std::thread::spawn` or `tauri::async_runtime::spawn`.', /Users/zhanglun/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tauri-runtime-wry-0.2.1/src/lib.rs:1124:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

my tauri.config.json

```json
{
...
 "allowlist": {
      "all": true,
      "shell": {
        "execute": false,
        "open": false
      },
      "notification": {
        "all":true
      },
      "fs": {
        "all": true
      }
    },
...
}
```

where I use API

```js
import { notification } from "@tauri-apps/api";

notification.requestPermission()
.then(() => {
  notification.sendNotification({ title: "Success" });
});
```

### Reproduction

1. run `yarn tauri dev`
2. click elements in the app window
3. app crashed

### Expected behavior

show notify message

### Platform and versions

```shell
yarn run v1.22.17
$ tauri info
 app:spawn Running "/Users/zhanglun/Documents/mine/rust-learning/tauri-app/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms


Operating System - Mac OS, version 12.1.0 X64

Node.js environment
  Node.js - 16.10.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.24.0
  yarn - 1.22.17

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/node_modules
/public
/src-tauri
/build
/.idea
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - React
```

**Comment by amrbashir** [comment]
Please upgrade to latest rc version, beta is not supported anymore.

**Comment by lucasfernog** [comment]
This was fixed on the RC.

**Comment by sietzekeuning** [comment]
I am using the latest version of the RC, but this problem still exists upon calling the notifications
