### ISSUE TITLE
window.tauri is undefined upon reloading

### ISSUE THREAD

**Issue by 3rd** [tauri-apps/tauri#377]
**Describe the bug**

> This might be the way it's supposed to be, let me know if that's the case.

Upon reloading the webview (manually or via HMR), `window.tauri` is `undefined`, and the APIs are unreachable.

**To Reproduce**
1. Run `tauri dev` and open the devtools console
2. Notice that `window.tauri` is populated
3. Reload
4. Try getting `window.tauri` again in console -> `undefined`

**Expected behavior**
I guess it shouldn't be undefined, maybe it's a security feature.

**Screenshots**

[**Video of the issue here**](https://u.gist.ro/selif/c5hwsqzr.webm)

**Platform and Versions (please complete the following information):**

OS: Linux(5.4.15-arch1-1) - linux/x64
Node: 12.14.1
NPM: 6.13.4
Yarn: 1.21.1
Rustc: 1.42.0-nightly

**Comment by nothingismagick** [comment]
This is a great issue - thankyou @3rd for filing it. I saw this a long time ago, but have been so focussed on the build chain that I haven't been actively developing with tauri for a while and it totally slipped my mind. I do recall the `reload` event triggering this, but HMR shouldn't. 

What framework are you using? That will help us to track it down.

**Comment by 3rd** [comment]
Thanks for being so responsive @nothingismagick !
It's a react + parcel setup, I uploaded the code here for testing: [demo-tauri-reload](https://github.com/3rd/demo-tauri-reload)

**Comment by lucasfernog** [comment]
This is the fix btw: https://github.com/zserge/webview/issues/171#issuecomment-448909787

i'm working on something that'll need this, so it'll probably ship next weekend.

**Comment by 3rd** [comment]
Can't seem to make it work on linux.

**Comment by nothingismagick** [comment]
Sorry this took so long - but it was resolved and will be landing in the next release cycle.

**Comment by rnons** [comment]
I still have this issue, and seems the PR was reverted, perhaps we should reopen this issue?
