### ISSUE TITLE
Still cant work with wasm in release mode [bug] 

### ISSUE THREAD

**Issue by ozgunozerk** [tauri-apps/tauri#4160]
### Describe the bug

I'm aware of #3897.
However the OP of #3897 marked it as solved, and claims it is working. That's why I did not want to re-open the issue.

I'm having a similar (or maybe the same) error. My application works in DEV, but the WASM related part does not work in PROD.

I did include `script-src 'wasm-unsafe-eval'` to my `tauri.conf.json` as below:
```    
"security": {
      "csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self' script-src 'wasm-unsafe-eval'"
    }
```

The code piece is related to polkadot/api, and uses WASM. 

The error I'm getting is:
```The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.```

The code piece uses `cryptoWaitReady()` as suggested above:
```ts
public async createRewardAddress(): Promise<string> {
    try {
      const mnemonic = mnemonicGenerate()
      const keyring = new Keyring({ type: 'sr25519', ss58Format: 2254 }) // 2254 is the prefix for subspace-testnet
      await cryptoWaitReady();
      util.infoLogger("CLIENT | cryptowait is ready")
      const pair = keyring.createFromUri(mnemonic)
      util.infoLogger("CLIENT | create from uri successful")
      this.mnemonic = mnemonic
      return pair.address
    } catch (error) {
      util.errorLogger(error)
      return "???"
    }
  }
```
The line that crashes it is:
`const pair = keyring.createFromUri(mnemonic)`, everything before works and I can track them in the log file.

I also opened an issue at polkadot/api (https://github.com/polkadot-js/api/issues/4833), but now I'm inclined to think that it is related to tauri.

### Reproduction

1. Copy the typescript code above and use it on the frontend.
2. The relevant polkadot libraries are as the following:
```ts
import { ApiPromise, Keyring } from "@polkadot/api"
import { mnemonicGenerate, cryptoWaitReady } from "@polkadot/util-crypto"
```
3. try to get the address in production mode (i used logging to be able to debug the prod)

### Expected behavior

I shouldn't have gotten any errors, and the line: `const pair = keyring.createFromUri(mnemonic)` should have worked.

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.62.0-nightly
  › cargo: 1.62.0-nightly
  › Rust toolchain: nightly-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.10
  › @tauri-apps/api [NPM]: 1.0.0-rc.5
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.4,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self' script-src 'wasm-unsafe-eval'
  › distDir: ../dist/pwa
  › devPath: http://localhost:8080/
  › framework: Vue.js (Quasar)
  › bundler: Webpack

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ .quasar
  ├─ src-pwa
  ├─ docs
  ├─ public
  ├─ .github
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src
```

### Additional context

Also tried `script-src: 'wasm-unsafe-eval'`, did not work either

**Comment by ozgunozerk** [comment]
A colleague of mine had this error in the very same context, might be helpful:
![image](https://user-images.githubusercontent.com/32795992/169084921-0a60d942-d7c1-4460-b22c-71970e1a0bd9.png)

**Comment by FabianLars** [comment]
Hmm, try disabling the hash injection for script-src via https://tauri.studio/v1/api/config#tauri.security.dangerousDisableAssetCspModification
Something like this `"dangerousDisableAssetCspModification": ["script-src"]`

**Comment by ozgunozerk** [comment]
Tried, did not work. Also tried: `dangerousDisableAssetCspModification: 'false'`, and did not work either.
Updating tauri now...
Any other suggestions? :)

**Comment by FabianLars** [comment]
To disable it _completely_ it would be `"dangerousDisableAssetCspModification": true` (without quotes), but since it complains about script-src it shouldn't matter if you disable _all_ or just script-src.
Either way, this should fix the error from [this screenshot](https://github.com/tauri-apps/tauri/issues/4160#issuecomment-1130183863) at least.

You can also try disabling the whole CSP mechanism by setting `"csp": null`

**Comment by FabianLars** [comment]
Ohh actually, i just saw that you have just `wasm-unsafe-eval` in `script-src`, but afaik once script-src is specified, default-src won't be applied anymore. And wasm-unsafe-eval is probably not supported in webkit yet(?)

**Comment by ozgunozerk** [comment]
@FabianLars 
it worked with `"csp": null`!!!

That's great for confirming we are at the right place and with the right key, it should work.
However, with the below, it still does not work, can you check one more time? 
Its either I'm using the wrong keys, or there is a typo like maybe a missing colon or something... Thanks in advance!
```
    "security": {
      "csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self' script-src 'wasm-unsafe-eval' dangerousDisableAssetCspModification: true"
    }
```

**Comment by FabianLars** [comment]
```json
    "security": {
      "csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self'; img-src: 'self'; script-src 'wasm-unsafe-eval' 'unsafe-eval'"
    }
```

But you probably want to look into making it more restrictive, like this for example
```json
    "security": {
      "csp": "default-src https: tauri: 'self'; img-src: 'self'; script-src 'wasm-unsafe-eval' 'unsafe-eval' 'self'"
    }
```

(in most of my personal project i use `"csp": "default-src 'self'"` btw, but i do every external communication in rust and no wasm or inline styles/scripts)

**Comment by ozgunozerk** [comment]
Thank you very much!

**Comment by lucasfernog** [comment]
Note that wasm-unsafe-eval doesn't work on macOS though (don't ask me why, wkwebview).
