### ISSUE TITLE
[bug] Can not download in front end

### ISSUE THREAD

**Issue by zhaoygcq** [tauri-apps/tauri#4633]
### Describe the bug

in the browser, we can use <a> like this:
```js
 const eleLink = document.createElement("a");
                eleLink.href = url;
                eleLink.download = `${title} - ${artist}`;
                eleLink.style.display = "none";
                document.body.appendChild(eleLink);
                eleLink.click();
                document.body.removeChild(eleLink);
```
to download file in front; but in tauri,this function can not take effect.

### Platform and versions

```shell
› OS: Mac OS 12.4.0 X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: 6.32.3
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-aarch64-apple-darwin
```

**Comment by amrbashir** [comment]
upstream: https://github.com/tauri-apps/wry/issues/349

**Comment by zhaoygcq** [comment]
it seems there is no answer; @amrbashir

**Comment by FabianLars** [comment]
> it seems there is no answer;

It's a tracking issue = it's not implemented yet.

**Comment by zhaoygcq** [comment]
> 

i see, thanks

**Comment by zhaoygcq** [comment]
> > it seems there is no answer;
> 
> It's a tracking issue = it's not implemented yet.

i see, thanks

**Comment by candrewlee14** [comment]
It looks like this has been solved upstream. 
Has that made it into any releases for tauri?
Are there any workarounds?

**Comment by matthme** [comment]
Yes, still not working on macOS with tauri 1.2.4. It does work on Linux though at least since tauri 1.2.3. So has it maybe only been partially fixed by https://github.com/tauri-apps/wry/pull/530?

**Comment by FabianLars** [comment]
it still needs to be implemented in Tauri. wry#530 just made it possible to do so (by adding new apis). 530 by itself shouldn't have added any behavior changes outside these new apis.

**Comment by reupen** [comment]
My experience of the out of the box behaviour of downloads (Tauri 1.3.0):

- On Windows, files are downloaded to the downloads folder. The web view shows a notification. If the file already exists, the new file is saved with a unique name.
- On Linux (Ubuntu 22.04), files are downloaded to the downloads folder. There is no notification from the web view. If the file already exists, it's deleted and no new file is saved.

(I don't have access to macOS to test there.)

**Comment by ManuelRauber** [comment]
> My experience of the out of the box behaviour of downloads (Tauri 1.3.0):
> 
> * On Windows, files are downloaded to the downloads folder. The web view shows a notification. If the file already exists, the new file is saved with a unique name.
> * On Linux (Ubuntu 22.04), files are downloaded to the downloads folder. There is no notification from the web view. If the file already exists, it's deleted and no new file is saved.
> 
> (I don't have access to macOS to test there.)

On macOS nothing seems to happen at all. No errors in the console, no file is downloaded.

At least not to this locations:

* Desktop
* Documents
* User Folder `~/`

**Comment by matthme** [comment]
Is there any plan for this being added to tauri still? It's still not working in tauri 1.4 almost one year after it being fixed upstream (it was planned apparently to be [added](https://github.com/tauri-apps/wry/issues/349#issuecomment-1284036316) to tauri 1.3). It's quite a critical issue for us.

**Comment by rosseyre** [comment]
Also critical for us if there is a chance of bringing this closer on the roadmap

**Comment by kirill-konshin** [comment]
Temporary solution:

```ts
import { saveAs } from 'file-saver';
import { save } from '@tauri-apps/api/dialog';
import { writeTextFile } from '@tauri-apps/api/fs';

export const downloadFile = async (filename, text, type = 'application/json') => {
    if (window.__TAURI__) {
        const filePath = await save({ defaultPath: filename });
        await writeTextFile(filePath, text);
    } else {
        saveAs(new Blob([text], { type }), filename);
    }
};
```

Don't forget to enable dialogs.

**Comment by Amerlander** [comment]
I use Tauri as a wrapper to serve static builds. I guess the temporary solution only works if I would change all links to use the `downloadFile`-function instead of just being links?

**Comment by ImageDeeply** [comment]
@FabianLars Would be useful to know if this issue is likely to be fixed in the 2.0 release.

**Comment by FabianLars** [comment]
i don't know either, probably not in 2.0.0 because of the audit 🤔

**Comment by gusxodnjs** [comment]
Is there any way to solve this part in the latest version of tauri?
In my case, the download code is in the external domain, so I need a way to resolve it in the Tauri app if possible.

**Comment by gusxodnjs** [comment]
I was in a situation where I couldn't install the tauri module on the front-end, and I eventually handled it like this. Hope it helps someone.

- Frontend
```js
export const useSaveFile = () => {
  const blobToBase64 = async (blob: Blob) => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader()
      reader.onloadend = () => {
        resolve((reader.result as string).split(',')[1])
      }
      reader.onerror = reject
      reader.readAsDataURL(blob)
    })
  }

  const saveFile = async (blob: Blob, fileName: string) => {
    if (window.isTauri) {
      const base64Data = await blobToBase64(blob)
      await invoke(`save_file`, { filename: fileName, data: base64Data })
    } else {
      saveAs(blob, fileName)
    }
  }

  return { saveFile }
}
```
- Backend
```rust
use base64::engine::general_purpose::STANDARD;
use base64::Engine;
use std::fs::File;
use std::io::Write;

#[tauri::command]
fn save_file(app_handle: AppHandle, filename: &str, data: &str) {
  let data = data.to_owned().clone();
  app_handle
    .dialog()
    .file()
    .set_file_name(filename)
    .save_file(move |file_path| {
      match STANDARD.decode(&data) {
        Ok(decoded_data) => {
          let file_path = file_path.unwrap().into_os_string().into_string().unwrap();
          match File::create(file_path) {
            Ok(mut file) => {
              if let Err(e) = file.write_all(&decoded_data) {
                println!("Failed to write to file: {}", e);
              }
            }
            Err(e) => {
              println!("Failed to create file: {}", e);
            }
          }
        }
        Err(e) => {
          println!("Failed to decode base64: {}", e);
        }
      }
    });
}
```

**Comment by wesloong** [comment]
> I was in a situation where I couldn't install the tauri module on the front-end, and I eventually handled it like this. Hope it helps someone.
> 
> * Frontend
> 
> ```js
> export const useSaveFile = () => {
>   const blobToBase64 = async (blob: Blob) => {
>     return new Promise((resolve, reject) => {
>       const reader = new FileReader()
>       reader.onloadend = () => {
>         resolve((reader.result as string).split(',')[1])
>       }
>       reader.onerror = reject
>       reader.readAsDataURL(blob)
>     })
>   }
> 
>   const saveFile = async (blob: Blob, fileName: string) => {
>     if (window.isTauri) {
>       const base64Data = await blobToBase64(blob)
>       await invoke(`save_file`, { filename: fileName, data: base64Data })
>     } else {
>       saveAs(blob, fileName)
>     }
>   }
> 
>   return { saveFile }
> }
> ```
> 
> * Backend
> 
> ```rust
> use base64::engine::general_purpose::STANDARD;
> use base64::Engine;
> use std::fs::File;
> use std::io::Write;
> 
> #[tauri::command]
> fn save_file(app_handle: AppHandle, filename: &str, data: &str) {
>   let data = data.to_owned().clone();
>   app_handle
>     .dialog()
>     .file()
>     .set_file_name(filename)
>     .save_file(move |file_path| {
>       match STANDARD.decode(&data) {
>         Ok(decoded_data) => {
>           let file_path = file_path.unwrap().into_os_string().into_string().unwrap();
>           match File::create(file_path) {
>             Ok(mut file) => {
>               if let Err(e) = file.write_all(&decoded_data) {
>                 println!("Failed to write to file: {}", e);
>               }
>             }
>             Err(e) => {
>               println!("Failed to create file: {}", e);
>             }
>           }
>         }
>         Err(e) => {
>           println!("Failed to decode base64: {}", e);
>         }
>       }
>     });
> }
> ```

that's nice

**Comment by bra1n** [comment]
As this is still not fixed, here's an updated "temporary" solution for Tauri v2:

```js
 import { saveAs } from 'file-saver';
 import { save } from "@tauri-apps/plugin-dialog";
 import { writeTextFile } from "@tauri-apps/plugin-fs";
 
 export const downloadFile = async (filename, text, type = 'application/json') => {
     if (window.__TAURI__) {
         const filePath = await save({ defaultPath: filename });
         await writeTextFile(filePath, text);
     } else {
         saveAs(new Blob([text], { type }), filename);
     }
 };
```

You'll also need to add these permissions to the capabilities JSON:
```
    "dialog:allow-open",
    "dialog:allow-save",
    "fs:allow-write-text-file",
```

**Comment by bra1n** [comment]
@FabianLars any news on getting this natively into Tauri for Mac?

**Comment by FabianLars** [comment]
Am i crazy or did i never mention the on_download method in this issue?? https://docs.rs/tauri/latest/tauri/webview/struct.WebviewWindowBuilder.html#method.on_download
That's embarrassing, sorry for that...

I'm not sure if this is something we would expose to the javascript side as well (open for api design suggestions either way, just in case), but i think it's fair to at least download into the Downloads dir automatically if on_download is not set.

**Comment by bra1n** [comment]
Right, but all of these just seem like a workaround for the issue that a plain `<a href="data:application/json;charset=utf-8,base64data..." download="file.json">Download</a>"` link works on all browsers, as well as Tauri on Windows and Linux, but not on Mac. 🤔

**Comment by FabianLars** [comment]
WKWebView has no built-in handling for this like the other webviews. It only provides "manual" apis that we use in on_navigation which in turn makes the use of `on_download` required (either in your own code, or with a potential fallback in tauri as mentioned above)

**Comment by bra1n** [comment]
> WKWebView has no built-in handling for this like the other webviews. It only provides "manual" apis that we use in on_navigation which in turn makes the use of `on_download` required (either in your own code, or with a potential fallback in tauri as mentioned above)

Thanks for the explanation! Unfortunately I have zero experience with Rust - where would I put the example code from [on_download](https://docs.rs/tauri/latest/tauri/webview/struct.WebviewWindowBuilder.html#method.on_download)? 
It looks like it would go into the `/src-tauri/src/main.rs` file, but if I put it there, I end up with 2 app windows. Presumably one from the `.run(tauri::generate_context!())` command and one from the on_download example that creates a new webview, right?
Or would it go into the `/src-tauri/build.rs`, since it calls `build()`?

**Comment by FabianLars** [comment]
In main.rs or lib.rs depending on where you already have a `tauri::Builder` line.

> Presumably one from the .run(tauri::generate_context!()) command and one from the on_download example that creates a new webview, right?

yep. If you want to keep configuring the window in tauri.conf.json you can add `create: false` to the window config (requires latest tauri version) and then do something like this
```rs
use tauri::{
  utils::config::{Csp, CspDirectiveSources, WebviewUrl},
  webview::{DownloadEvent, WebviewWindowBuilder},
};

tauri::Builder::default()
  .setup(|app| {
    let handle = app.handle();
    // `get(0)` assumes that we're talking about the first window in the tauri.conf.json window config array.
    let webview_window = WebviewWindowBuilder::from_config(handle, &app.config().app.windows.get(0).unwrap().clone())
      .on_download(|webview, event| {
        match event {
          DownloadEvent::Requested { url, destination } => {
            println!("downloading {}", url);
            *destination = "/home/tauri/target/path".into();
          }
          DownloadEvent::Finished { url, path, success } => {
            println!("downloaded {} to {:?}, success: {}", url, path, success);
          }
          _ => (),
        }
        // let the download start
        true
      })
      .build()?;

    Ok(())
  });
```

**Comment by bra1n** [comment]
> yep. If you want to keep configuring the window in tauri.conf.json you can add `create: false` to the window config (requires latest tauri version) and then do something like this
> ...

Unfortunately, your example is not working:

```
error[E0599]: no method named `on_download` found for enum `Result` in the current scope
   --> src/main.rs:15:16
    |
14  |               let webview_window = WebviewWindowBuilder::from_config(handle, &app.config().app.windows.get(0).unwrap().clone())
    |  __________________________________-
15  | |               .on_download(|webview, event| {
    | |               -^^^^^^^^^^^ method not found in `Result<WebviewWindowBuilder<'_, Wry<EventLoopMessage>, AppHandle>, Error>`
    | |_______________|
    |
    |
note: the method `on_download` exists on the type `WebviewWindowBuilder<'_, tauri_runtime_wry::Wry<EventLoopMessage>, AppHandle>`
   --> C:\Users\Docker\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-2.2.2\src\webview\webview_window.rs:301:3
    |
301 | /   pub fn on_download<F: Fn(Webview<R>, DownloadEvent<'_>) -> bool + Send + Sync + 'static>(
302 | |     mut self,
303 | |     f: F,
304 | |   ) -> Self {
    | |___________^
help: use the `?` operator to extract the `WebviewWindowBuilder<'_, tauri_runtime_wry::Wry<EventLoopMessage>, AppHandle>` value, propagating a `Result::Err` value to the caller
    |
14  |             let webview_window = WebviewWindowBuilder::from_config(handle, &app.config().app.windows.get(0).unwrap().clone())?
    |                                                                                                                              +
```

**Comment by FabianLars** [comment]
I typed it on my phone directly in github so that doesn't surprise me that much 🙃 sorry though

The error should be accurate so just append a `?` here:
```rs
let webview_window = WebviewWindowBuilder::from_config(handle, &app.config().app.windows.get(0).unwrap().clone())? // <- this one
  .on_download()
```

**Comment by bra1n** [comment]
Thanks, it's not throwing any errors anymore, just a few warnings:
```
warning: unused imports: `CspDirectiveSources`, `Csp`, `WebviewUrl`
 --> src/main.rs:5:19
  |
5 |   utils::config::{Csp, CspDirectiveSources, WebviewUrl},
  |                   ^^^  ^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused variable: `webview_window`
  --> src/main.rs:21:15
   |
21 |           let webview_window = WebviewWindowBuilder::from_config(handle, &app.config().app.windows.get(0).unwrap().clone())?
   |               ^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_webview_window`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `webview`
  --> src/main.rs:22:27
   |
22 |             .on_download(|webview, event| {
   |                           ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_webview`
```
On top of that, I also don't know what to replace the `destination` with, since I don't have a default download path or anything like that. 🤔 Maybe I'll stick with the workaround for now, as that also includes a save file dialogue.

**Comment by FabianLars** [comment]
> On top of that, I also don't know what to replace the destination with, since I don't have a default download path or anything like that. 🤔 Maybe I'll stick with the workaround for now, as that also includes a save file dialogue.

Well if you want to match the browser behavior you could prepend the downloads dir on macos/linux (already set on windows). In an upcoming release of wry those suggested paths will be consistent, as in, they will all start in the downloads dir and have a relatively sane filename.
In an upcoming Tauri release i'll also try to squeeze in a [PR](https://github.com/tauri-apps/tauri/pull/14006) that'll automatically allow downloads on local urls (not set on the latter yet).

The plan is to release wry and tauri this weekend.
