### ISSUE TITLE
System Tray icon is not getting removed immediately after "app.exit(0)". Its getting removed on hover.

### ISSUE THREAD

**Issue by shanu-mol** [tauri-apps/tauri#5533]
![CPT2211031124-245x157](https://user-images.githubusercontent.com/91492374/199655852-3c859913-07dd-4977-8537-675fde201c9e.gif)

I have added Gif file.
When I click Quit from System Tray handler the code executed is :- app.exit(0)
![image](https://user-images.githubusercontent.com/91492374/199656124-b1f7dbc0-82d7-44e1-b3f8-d058532bd6c0.png)

OS : Windows 10
tauri = { version = "1.1.1", ... }

**Comment by FabianLars** [comment]
Fixed in https://github.com/tauri-apps/tauri/pull/5245, will be available with v1.2 (no ETA yet, but should be fairly soon)

**Comment by wkl007** [comment]
https://user-images.githubusercontent.com/23228335/205606719-4576c7c7-b0e5-43f2-b740-f5afb62069de.mp4

tauri 1.2.1 still have this problem，please help us @FabianLars 

https://github.com/wkl007/tauri-plugin-single-instance/blob/dev/examples/emit-event/src-tauri/Cargo.toml

**Comment by amrbashir** [comment]
@wkl007 thanks for the report, the released fix was for the rust side, I will open a PR shortly for the JS side.

Edit: https://github.com/tauri-apps/tauri/pull/5765

**Comment by wkl007** [comment]
Thank you very much @amrbashir
