### ISSUE TITLE
[bug] Scrollbar missing on linux

### ISSUE THREAD

**Issue by jedfonner** [tauri-apps/tauri#6294]
### Describe the bug

Vertical and horizontal scrollbars are not visible when running `dev` on linux

### Reproduction

1. On linux, run `npm create tauri-app`
2. Choose any flavor
3. Open the main UI (e.g., index.html or /routes/+page.svelte)
4. Add a bunch of content to make the UI taller and/or wider than the window - see [index.zip](https://github.com/tauri-apps/tauri/files/10761681/index.zip)
5. run `npm run tauri dev`
6. Notice that you can scroll with arrow keys or mouse scrollwheel, but no visible scrollbars are present

### Expected behavior

Scrollbars should be visible

### Platform and versions

```
> tauri-test2@0.0.0 tauri
> tauri "info"


Environment
  › OS: Linux 22.04 X64
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: 7.14.0
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src

App directory structure
  ├─ .vscode
  ├─ node_modules
  ├─ src
  └─ src-tauri
```

### Additional context

https://user-images.githubusercontent.com/344481/219508726-1b87cbe2-f857-4992-ab2a-bb457e140557.mp4

**Comment by Apogeum12** [comment]
There are some issue with scrollbar on Linux, for me scroll show without any problem, but when I hover the scroll then it's crashing whole scrollbar. I tried CSS styles like -webkitscrollbar..... etc. but nothing helped :( 

[Nagranie ekranu z 2023-02-18 19-17-03.webm](https://user-images.githubusercontent.com/35242996/219882138-597d5eca-84cb-4f0c-b963-a9aed7a92d17.webm)

Tauri system info:
```sh
> tauri info


Environment
  › OS: Red Hat Enterprise Linux 37.0.0 X64
  › Node.js: 18.14.0
  › npm: 9.3.1
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ src-tauri
  ├─ .vscode
  ├─ src
  ├─ public
  ├─ node_modules
  └─ dist
```

**Comment by jedfonner** [comment]
I just tried building and can confirm that the scrollbar IS visible in the built appImage.  So it seems this issue is specific to running `tauri dev`.

**Comment by nikhil-prabhu** [comment]
> I just tried building and can confirm that the scrollbar IS visible in the built appImage. So it seems this issue is specific to running `tauri dev`.

I tried this as well, and can confirm that the scrollbar does work in the AppImage and deb, but is not visible in either `tauri dev` or when running the built release binary directly.

```
❯ yarn tauri info
yarn run v1.22.19
$ tauri info

Environment
  › OS: openSUSE 20230220 X64
  › Node.js: 18.13.0
  › npm: 8.19.3
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ .devcontainer
  ├─ .cargo
  ├─ .git
  ├─ .vscode
  ├─ src
  ├─ target
  ├─ src-tauri
  ├─ dist
  └─ node_modules
Done in 15.69s.
```

**Comment by fetzsav** [comment]
I see you’re using Red Hat. I want to try to replicate on another linux distro and see.

Can you try adding 
`overflow: auto`
to the root or body element of your css?

**Comment by Apogeum12** [comment]
Hi @fetzsav 
I tried overflow: auto in root, html, *, div where the all elements are, didn't help for me. I'll be trying in the release version, but isn't available for now rpm version, so I'm working only with dev mode.

**Comment by amrbashir** [comment]
fixed in https://github.com/tauri-apps/wry/pull/897

**Comment by jedfonner** [comment]
Doesn't seem that I can use the latest release of wry because tauri is still at v1.4.1 which brings in tauri-runtime-wry v0.14.0 which brings in wry v0.24.3 which doesn't have this fix yet.  And it looks like tauri 1.4.1 is the last of the v1.x releases.  So I'll have to wait for tauri v2 to become stable to know if this is fixed.  I did try updating just wry but it causes a bunch of unmet dependency issues.

**Comment by zica87** [comment]
@amrbashir
The scrollbar is still not showing.
The bug is not fixed.

```
[✔] Environment
    - OS: EndeavourOS Rolling Release X64
    ✔ webkit2gtk-4.0: 2.42.4
    ✔ rsvg2: 2.57.1
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (2023-11-14)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 21.6.0
    - pnpm: 8.14.1
    - npm: 10.3.0

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.6
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

**Comment by Lamby777** [comment]
> @amrbashir The scrollbar is still not showing. The bug is not fixed.
> 
> ```
> [✔] Environment
>     - OS: EndeavourOS Rolling Release X64
>     ✔ webkit2gtk-4.0: 2.42.4
>     ✔ rsvg2: 2.57.1
>     ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
>     ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
>     ✔ rustup: 1.26.0 (2023-11-14)
>     ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
>     - node: 21.6.0
>     - pnpm: 8.14.1
>     - npm: 10.3.0
> 
> [-] Packages
>     - tauri [RUST]: 1.5.4
>     - tauri-build [RUST]: 1.5.1
>     - wry [RUST]: 0.24.7
>     - tao [RUST]: 0.16.6
>     - @tauri-apps/api : not installed!
>     - @tauri-apps/cli [NPM]: 1.5.9
> 
> [-] App
>     - build-type: bundle
>     - CSP: unset
>     - distDir: ../src
>     - devPath: ../src
> ```

Same issue for me.

```
[✔] Environment
    - OS: Arch Linux Rolling Release X64
    ✔ webkit2gtk-4.0: 2.44.2
    ✔ rsvg2: 2.58.1
    ✔ rustc: 1.80.0-nightly (1ba35e9bb 2024-05-25)
    ✔ cargo: 1.80.0-nightly (a8d72c675 2024-05-24)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-x86_64-unknown-linux-gnu (default)
    - node: 22.2.0
    - npm: 10.8.0

[-] Packages
    - tauri [RUST]: 1.6.7
    - tauri-build [RUST]: 1.5.2
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.5.14
    - @tauri-apps/api [NPM]: 1.5.6
    - @tauri-apps/cli [NPM]: 1.5.14

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite
```

On Windows it shows up fine.
