### ISSUE TITLE
[bug] Failed to bundle an NSIS installer under linux in tauri 2.0.0-alpha.8

### ISSUE THREAD

**Issue by karandit** [tauri-apps/tauri#6743]
### Describe the bug

While trying to cross-compile a hello-world tauri-app for Windows from Linux (docker), I got at the very end an error at the bundling phase complaining about some missing folder. 

### Reproduction

0. `apt-get install --no-install-recommends -y nsis libwebkit2gtk-4.1-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev`
1. `cargo create-tauri-app`
2. choose Rust, Vanilla
3. change the bundle identifier in `tauri.conf.json > tauri > bundle > identifier` to something else than its current value
4. bump  version in `Cargo.toml > dependencies > tauri` to `2.0.0-alpha.8` to get rid off the `error: failed to select a version for tauri.` problem
5. `cargo tauri build --target x86_64-pc-windows-msvc`

### Expected behavior

the command executes successfully and an NSIS bundler is created

### Platform and versions

```text
WARNING: no lock files found, defaulting to npm

[✔] Environment
    - OS: Debian Unknown X64
    ✔ webkit2gtk-4.1: 2.40.0
    ✔ rsvg2: 2.54.5
    ✔ rustc: 1.68.2 (9eb3afe9e 2023-03-27)
    ✔ Cargo: 1.68.2 (6feb7c9cf 2023-03-26)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: 1.68.2-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.15.0
    - npm: 9.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.8
    - tauri-build [RUST]: no manifest (1.2.1, 2.0.0-alpha.4)
    - wry [RUST]: 0.27.3
    - tao [RUST]: 0.18.3
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.8

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

### Stack trace

```text
Compiling reproduce-bug v0.0.0 (/usr/src/examples/reproduce-bug/src-tauri)
    Finished release [optimized] target(s) in 18.47s
        Warn Cross-platform compilation is experimental and does not support all features. Please use a matching host system for full compatibility.
        Warn ignoring WindowsMsi
        Warn NSIS directory is missing some files. Recreating it.
        Info Verifying NSIS package
 Downloading https://github.com/tauri-apps/binary-releases/releases/download/nsis-plugins-v0/NSIS-ApplicationID.zip
        Info extracting NSIS ApplicationID plugin
       Error failed to bundle project: `No such file or directory (os error 2)`
```

**Comment by amrbashir** [comment]
Could you try running with `--verbose` flag?

**Comment by karandit** [comment]
actually I've already fixed the problem, a PR is coming. 
The problem is a missing`x86-unicode` folder creation  before this [part](https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler/src/bundle/windows/nsis.rs#L103)

**Comment by gudaoxuri** [comment]
Upgraded to the latest version and still have the same problem.

```
[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.1: 2.44.0
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 21.6.0
    - pnpm: 9.1.1
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.19
    - tauri-build [RUST]: 2.0.0-beta.15
    - wry [RUST]: 0.39.5
    - tao [RUST]: 0.28.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.11
    - @tauri-apps/cli [NPM]: 2.0.0-beta.17

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
 ```

`` pnpm tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc --verbose``

```
...
    Debug [ureq::unit] writing prelude: GET /github-production-release-asset-2e65be/580520344/a0828d2d-7113-4581-909b-20ecc733ce7a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240515%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240515T043811Z&X-Amz-Expires=300&X-Amz-Signature=b546474b041197f050134ec7ae47417f1e958be67b5dba5da558f75dc2ae561a&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=580520344&response-content-disposition=attachment%3B%20filename%3Dnsis_tauri_utils.dll&response-content-type=application%2Foctet-stream HTTP/1.1
Host: objects.githubusercontent.com
User-Agent: ureq/2.9.6
Accept: */*
accept-encoding: gzip
    Debug [ureq::response] Streaming body until content-length: 28672
    Debug [ureq::unit] response 200 to GET https://objects.githubusercontent.com/github-production-release-asset-2e65be/580520344/a0828d2d-7113-4581-909b-20ecc733ce7a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240515%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240515T043811Z&X-Amz-Expires=300&X-Amz-Signature=b546474b041197f050134ec7ae47417f1e958be67b5dba5da558f75dc2ae561a&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=580520344&response-content-disposition=attachment%3B%20filename%3Dnsis_tauri_utils.dll&response-content-type=application%2Foctet-stream
    Debug [ureq::pool] adding stream to pool: https|objects.githubusercontent.com|443 -> Stream(RustlsStream)
    Debug [ureq::stream] dropping stream: Stream(RustlsStream)
    Debug [ureq::stream] dropping stream: Stream(RustlsStream)
    Info [tauri_bundler::bundle::windows::util] validating hash
    Error [tauri_cli_node] failed to bundle project: `No such file or directory (os error 2)`
```
