### ISSUE TITLE
[bug] input[required] missing message when invalid form 

### ISSUE THREAD

**Issue by Apogeum12** [tauri-apps/tauri#6755]
### Describe the bug

When we complete the form and some input is invalid for example type="mail" then in required message box isn't text message.

### Reproduction

Add `<form><label>Ex.</label><input  type="mail" required/></form>` into React Vite skeleton app.

### Expected behavior

Show message into required box when input is invalid.

### Platform and versions

```text
┌💁  euuki @ 💻  litepc in 📁  test
└❯ npm run tauri info

> test@0.0.0 tauri
> tauri info


Environment
  › OS: Red Hat Enterprise Linux 37.0.0 X64
  › Node.js: 18.15.0
  › npm: 9.5.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.68.2
  › cargo: 1.68.2
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ src-tauri
  ├─ .vscode
  ├─ src
  ├─ public
  └─ node_modules
```

### Additional context

[Nagranie ekranu z 2023-04-20 10-44-58.webm](https://user-images.githubusercontent.com/35242996/233312223-3b4eeedc-e55a-48cf-b013-f7fbc6267be0.webm)

**Comment by amrbashir** [comment]
This feels like a problem in the desktop environment tooltips as it works fine on my KDE and WSL2. @FabianLars can you confirm on the DEs you have?

**Comment by FabianLars** [comment]
only wsl2 worked for me too, in "real" linux envs it was always broken. Here's what i tested:

Ubuntu 22.04 + Gnome (fresh VM)
Xubuntu 22.04 + Xfce (fresh VM)
fedora 37 + Gnome - wayland and x11
fedora 37 + KDE - wayland and x11

**Comment by Apogeum12** [comment]
@FabianLars So it isn't possible to do something with this? I'll trying latter setCustomValidity() in JS maybe it work.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/setCustomValidity

**Comment by amrbashir** [comment]
It is working fine on my KDE and Gnome
![2023-05-04_01-26](https://user-images.githubusercontent.com/48618675/236064310-0d068582-ec46-4b7c-97e2-460db7b9628d.png)
![236057221-6af01753-461f-45a0-bf15-3df199db139b](https://user-images.githubusercontent.com/48618675/236064316-7f00212c-a767-4ec7-a21b-64436c7668b0.png)

**Comment by amrbashir** [comment]
maybe it was a bug that got solved in a newer webkit2gtk? could you guys try with the latest `dev` branch of `wry`?

**Comment by FabianLars** [comment]
Nope, still broken:
![grafik](https://user-images.githubusercontent.com/30730186/236154764-731ab68c-afe7-488b-82bb-aac705c999c7.png)

**Comment by Apogeum12** [comment]
For me also doesn't work
[Nagranie ekranu z 2023-05-04 10-49-21.webm](https://user-images.githubusercontent.com/35242996/236156052-d9cc0f27-3369-406f-a46e-a8833c8c7194.webm)

I have a webkit2gtk4.0, maybe it's need a webkit2gtk5.0? But I can't installed yet this packages because probably break my system...

![webkit2gtk](https://user-images.githubusercontent.com/35242996/236158359-6ad5ca08-8075-4685-a0fc-e9396af61ddf.png)

When I'll upgrade to fedora 38 I'll check this.

**Comment by 0-don** [comment]
![Image](https://github.com/user-attachments/assets/3b0242dd-eb55-421e-9b0e-cc56b54a53e8)

same issue on required input, I am using tauri v2 with kde plasma

**Comment by willm** [comment]
I still have this problem in gnome
