### ISSUE TITLE
[feat] Add "run as administrator" flag 

### ISSUE THREAD

**Issue by Aviv-Frenkel** [tauri-apps/tauri#7173]
### Describe the problem

I would like my application to run with administrator privileges by default

### Describe the solution you'd like

Optional flag in `tauri.conf.json` file to set whether the application should run as administrator by default or not

### Alternatives considered

Right now I'm trying to do this from the Rust entry point

### Additional context

When the user opens the app (not the installer), I want Window's UAC prompt to be shown to grant administrator privileges

**Comment by FabianLars** [comment]
Thanks for the request!

I don't want to decide if we want a config for this or not (though i do tend to "No") but for anyone stumbling upon this, you can do this with tauri v1.3 in your `build.rs` file using the [app_manifest](https://docs.rs/tauri-build/latest/tauri_build/struct.WindowsAttributes.html#method.app_manifest) method:
```rs
let mut windows = tauri_build::WindowsAttributes::new();
windows = windows.app_manifest(r#"
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
        type="win32"
        name="Microsoft.Windows.Common-Controls"
        version="6.0.0.0"
        processorArchitecture="*"
        publicKeyToken="6595b64144ccf1df"
        language="*"
      />
    </dependentAssembly>
  </dependency>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
        <requestedPrivileges>
            <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
        </requestedPrivileges>
    </security>
  </trustInfo>
</assembly>
"#);
tauri_build::try_build(
  tauri_build::Attributes::new().windows_attributes(windows)
).expect("failed to run build script");
```
(Note the `dependency` part is needed for the dialog, so if you don't use the dialog module and don't use the updater's default dialog you can remove that part)

**Comment by amrbashir** [comment]
I agree with @FabianLars , will close this for now and reconsider if more people request it.

**Comment by fortserious** [comment]
Fabian's post worked great, but I'm running into an issue with the NSIS installer where a program that requires administrator access won't run from the setup exe, even if "Run after completing install" is checked. I think the issue is due to this call in the installer.nsi:

`nsis_tauri_utils::RunAsUser "$INSTDIR\${MAINBINARYNAME}.exe" ""`

nsis_tauri_utils::RunAsUser explicitly runs as a user from an elevated installer, but since the app requires elevation now, it fails to run. Is there a way to conditionally run this function based on the app_manifest?

As a workaround, I've copied the installer.nsi to my own template, added it to tauri.conf.json, and replaced the RunAsUser lines with: `Exec "$INSTDIR\${MAINBINARYNAME}.exe"` - but this is a bit cumbersome. Any other ideas?

**Comment by sapidzzy** [comment]
> Fabian's post worked great, but I'm running into an issue with the NSIS installer where a program that requires administrator access won't run from the setup exe, even if "Run after completing install" is checked. I think the issue is due to this call in the installer.nsi:
> 
> `nsis_tauri_utils::RunAsUser "$INSTDIR\${MAINBINARYNAME}.exe" ""`
> 
> nsis_tauri_utils::RunAsUser explicitly runs as a user from an elevated installer, but since the app requires elevation now, it fails to run. Is there a way to conditionally run this function based on the app_manifest?
> 
> As a workaround, I've copied the installer.nsi to my own template, added it to tauri.conf.json, and replaced the RunAsUser lines with: `Exec "$INSTDIR\${MAINBINARYNAME}.exe"` - but this is a bit cumbersome. Any other ideas?

I've also encountered the same issue, so I hope there is a "Run as Administrator" configuration to resolve the above issues.

**Comment by ata1704** [comment]
We could work with @FabianLars solution but the issues we are facing now is, that we need to run VS Code as admin to work with `tauri dev` in the VS Code terminal. :-(

**Comment by FabianLars** [comment]
If your app can run without admin in development you can apply the manifest conditionally via `tauri_build::is_dev()`.
Otherwise this is one of the drawbacks of wanting the whole app run as admin 🤷 but I mean, having to run an external terminal instead of the built-in one isn't too bad of a workaround in this context...

**Comment by Curtion** [comment]
> We could work with @FabianLars solution but the issues we are facing now is, that we need to run VS Code as admin to work with `tauri dev` in the VS Code terminal. :-(

Using the `Inline` mode of `Sudo for Windows` can solve this problem.

**Comment by Curtion** [comment]
@FabianLars More importantly, in addition to the software not being able to start after NSIS installation, the program run as administrator also fails to start automatically after using the `updater`.

**Comment by FabianLars** [comment]
Re-opening because of the issue in the [comment above](https://github.com/tauri-apps/tauri/issues/7173#issuecomment-2482697234). I'm still not really sold on the flag but i'm okay with it if we can't fix it in the installers without it.

**Comment by Legend-Master** [comment]
Just a note that the problem of the NSIS installer can't launch the app if it's marked as require admin right was tracked in #11844, and fixed in https://github.com/tauri-apps/nsis-tauri-utils/pull/40

**Comment by sascha1337** [comment]
wix still broken, and how to do goddamn autostart with admin ?
