### ISSUE TITLE
(bundler): Static build for windows should be handled auto-magically

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tauri#719]
**Is your feature request related to a problem? Please describe.**
Installed a bundled app on fresh Windows VM and I got the error that `msvcp140.dll` is missing.

**Describe the solution you'd like**
Having a static build automatically handled by the bundler.

Create a file called .cargo\config
```
[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
```
**Describe alternatives you've considered**
Need to install Visual C++ Redistributable on the target machine (BAD IDEA)

**Comment by lucasfernog** [comment]
If this is just a Cargo config missing then I think we should have that file on our init template.

**Comment by jwenjian** [comment]
My silly question, where should I put this `.cargo` folder? in the `src-tauri`? or my project root folder?

**Comment by lucasfernog** [comment]
`src-tauri` @jwenjian

**Comment by jwenjian** [comment]
@lucasfernog thx, I have already add such config file and build a new release file for Windows OS, but since I have no Windows laptop, can't validate it by myself.

**Comment by brendanosborne** [comment]
I rolled out a small beta test recently and the first two users had this msvcp140.dll is missing issue.

@lucasfernog I noticed in the Discord #windows chat back in 07/12/20 you were having trouble reproducing this issue. I am able to reproduce it using Windows Sandbox: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview

**Comment by amrbashir** [comment]
@brendanosborne we recently released the beta, can you try again with that, the missing dll should be fixed.

**Comment by brendanosborne** [comment]
@amrbashir I just built a fresh app this morning to test using vue-cli-plugin-tauri - maybe that is not targeting the new beta release yet?

**Comment by amrbashir** [comment]
indeed, the `vue-cli-plugin-tauri` will be updated soon. For now you can try using `yarn create tauri-app --recipe vuecli`

**Comment by brendanosborne** [comment]
I'm still seeing the same error with `yarn create tauri-app --recipe vuecli`

[tauri]: running info

Operating System - Windows_NT(10.0.19042) - win32/x64
Microsoft Edge - 44.19041.423.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 15.11.0
  tauri.js - 0.14.1

Rust environment
  rustc - 1.51.0
  cargo - 1.51.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 7.6.0
  yarn - 1.22.10

App directory structure
/.git
/dist
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.11.1
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - unset
  devPath - unset

**Comment by amrbashir** [comment]
@brendanosborne I am so sorry for the inconvenience, apparently we use `vue-cli-plugin-tauri`(which still needs to be updated) in `create-tauri-app` for `vuecli` recipe. 
Can you try again `yarn create tauri-app` and choose another recipe, I'd recommend the `vanilla` just to test quickly.

If you have further question, join us on [Discord](https://discord.gg/HsnKWQcE)

**Comment by lucasfernog** [comment]
This was fixed on #1368 , please reopen if you face any issues.

**Comment by brendanosborne** [comment]
Unfortunately still seeing the same result with the `yarn create tauri-app` - `vanilla`.
It looks like I'm using the latest and greatest... the `package.json` contains:
```
  "dependencies": {
    "tauri": "0.14.1"
  },
  "devDependencies": {
    "@tauri-apps/cli": "^1.0.0-beta-rc.1"
  }
```

I don't seem to be able to reopen the issue.

**Comment by amrbashir** [comment]
@brendanosborne
Bad news, there is a bug in `create-tauri-app` which installed the old version of tauri.

Good news, the `vue-cli-plugin-tauri` is now updated with the latest changes. Try again with that.

**Comment by brendanosborne** [comment]
Thanks you. Confirming it is now working in the Windows Sandbox!
