### ISSUE TITLE
Causing AppImage to crash on NixOS

### ISSUE THREAD

**Issue by donni-h** [tauri-apps/tauri#7734]
https://github.com/tauri-apps/tauri/blob/af3268a4be69e2dee72ba867ee54bc36d12712e6/core/tauri-utils/src/lib.rs#L299-L309

Heya folks, this bug has been reported before in #7046. 
I have tracked down the root cause and it appears to be this check.
I don't think that this is the best way to actually check, whether we're actually running on an AppImage and it certainly causes crashing on NixOS, though I haven't found a cleaner alternative.

I would be very thankful, if someone could take a look and maybe help us figure out how to fix it, as it might also affect some other distributions. ❤️

**Comment by poelzi** [comment]
@FabianLars  Why was this bug closed without comment or checkin ?

**Comment by FabianLars** [comment]
This issue was opened 3 times so the chain was broken, but it was fixed here: https://github.com/tauri-apps/tauri/pull/7843

**Comment by RAVENz46** [comment]
This issue is still occurring. Is it just that the bug fixes have not been reflected yet?

**Comment by FabianLars** [comment]
@RAVENz46 The change was included in tauri-utils 1.5.0 so make sure you're using the latest tauri versions and run `cargo update` in the src-tauri dir to force nested deps to update.

**Comment by RAVENz46** [comment]
@FabianLars Sadly, that is not solution for appimage. But thank you, now I understand what cause this issue. I will try build from source.

**Comment by RAVENz46** [comment]
Wait, now I realized that tauri-utils seems version 2.0.0-alpha.
Here is I try to launch [binglite](https://github.com/I-Info/BingLite) appimage build.
```
thread 'main' panicked at '`APPDIR` or `APPIMAGE` environment variable found but this application was not detected as an AppImage; this might be a security issue.', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-utils-2.0.0-alpha.5/src/lib.rs:207:11
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by FabianLars** [comment]
Same logic applies there, this project uses a quite old alpha version from before the fix was added.

**Comment by RAVENz46** [comment]
@FabianLars Alright, thanks for you help!
