### ISSUE TITLE
[bug]  unknown feature `proc_macro_span_shrink`

### ISSUE THREAD

**Issue by drharryhe** [tauri-apps/tauri#7805]
### Describe the bug

 cargo install create-tauri-app --locked
    Updating crates.io index
  Installing create-tauri-app v3.7.3
   Compiling libc v0.2.139
   Compiling typenum v1.16.0
   Compiling version_check v0.9.4
   Compiling crc32fast v1.3.2
   Compiling proc-macro2 v1.0.59
   Compiling quote v1.0.28
   Compiling unicode-ident v1.0.8
   Compiling cfg-if v1.0.0
   Compiling rle-decode-fast v1.0.3
   Compiling proc-macro-hack v0.5.20+deprecated
   Compiling syn v1.0.109
   Compiling generic-array v0.14.6
   Compiling libflate_lz77 v1.2.0
   Compiling io-lifetimes v1.0.5
   Compiling adler32 v1.2.0
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /Users/harry/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.59/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to previous error

### Platform and versions

```text
●CPU: Apple M1 Pro
●ProductName: macOS
●ProductVersion: 13.4.1
●BuildVersion: 22F82
```

**Comment by amrbashir** [comment]
Can you try with the `--locked` flag?

**Comment by drharryhe** [comment]
as in descript, --lcoked has been used:
cargo install create-tauri-app --locked

**Comment by drharryhe** [comment]
actually， the command succeeded without --locket.
thanks to @amrbashir

**Comment by amrbashir** [comment]
Thank you, it should be fixed in the upcoming release of create-tauri-app

**Comment by gosuwachu** [comment]
@amrbashir this is still not fixed, I have followed the instructions from https://tauri.app/ and ran:

```
cargo install create-tauri-app --locked
cargo create-tauri-app
```

The same error appeared as reported in this issue. I can't re-open it, but I don't want to create another issue.

**Comment by FabianLars** [comment]
@gosuwachu Does it work without the `--locked` option? Also, what rust version are you using?

**Comment by gosuwachu** [comment]
Yes, it works without the `--locked` option. Maybe it is just a matter of updating the instructions then, but I wanted to flag this up, as it will turn away a lot of people.
