### ISSUE TITLE
[bug] Windows WebView2 creation error: Parameter is incorrect

### ISSUE THREAD

**Issue by chirok11** [tauri-apps/tauri#7897]
### Describe the bug

Sometimes, I am receiving errors in my Sentry.
They all look like this.
`CreateWebview: failed to create webview: WebView2 error: WindowsError(Error { code: 0x80070057, message: The parameter is incorrect. })`
I don't know why it could be, and don't know how to solve them or where should I look into, to discover it.
The problem is floating, because for some PC's I see events, that related to successfully running application (that means client was able to start application).

I am sure, that customer have installed WebView due to JSON of error in Sentry, here is DLL of WebView presented, and version here too.

Versions of Windows where I saw this error:
windows 10.0.22621,
windows 10.0.19045,
windows 10.0.19044,
windows 10.0.19042,
windows 10.0.18363,
windows 10.0.17763,
windows 6.3.9600.

One customer told me, that he saw this error (then I saw error in Sentry), but next run was success.

### Reproduction

Have no idea how to reproduce it,
tried with installing fresh and clean versions, my attempt was successfull, and I wasn't able to reproduce bug.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 117.0.2045.36
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.72.1 (d5c2e9c34 2023-09-13)
    ✔ Cargo: 1.72.1 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.17.0
    - yarn: 1.22.19
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ***
    - devPath: **
    - framework: ***
    - bundler: ***
```

### Additional context

``
``

**Comment by chirok11** [comment]
first sentry error json
https://pastecode.dev/s/sGHGZw2TDj
second sentry error
https://pastecode.dev/s/hXmuKgvN0K

will attach more when I'll have them.
@FabianLars could confirm that I don't have any specific in `src-tauri/main.rs`.

**Comment by chirok11** [comment]
4 more errors. (files attached to link below)
https://pastecode.dev/s/fCD9AjN5In

**Comment by dceddia** [comment]
I've seen this error too. I get a couple of them:

- `The parameter is incorrect.` (0x80070057)
- `The system cannot find the file specified.` and `File not found.` (0x80070002)

(and some variations in non-English languages)

I've had a few users who say the app fails to launch, and then it has turned out that they uninstalled the WebView2 components from Windows (trying to un-bloat their systems, I guess). And then after reinstalling WebView2, the app runs fine. The thing is... I'm not sure if these errors are correlated with those user reports. So this could be a red herring.

Just in case that actually is the cause here, I was thinking of trying to catch this error on startup, and display a message box telling the user to reinstall WebView2. It'd be a shot in the dark though.

I also wish I could figure out how to get Sentry to give me stack traces! I've tried uploading the debug info without much luck, and I wonder if I'm just not uploading the right files or something. If anyone has gotten this working I'd love to know how! 😁

**Comment by chirok11** [comment]
If we're talking about Windows platform, you just have to upload .pdb
I have this action in my GitHub Workflow file
 run: sentry-cli debug-files upload -o **redacted**-p **redacted** src-tauri\target\release\app.pdb
and as result I see full stacktrace.

Regarding issue, I am showing message box regarding WebView2 that it is not installed and opening default browser with download link, but I dont think that is good solution how we should solve this trouble.

I see these errors every day, not a lot, but, one thing that I worry about that I/we don't know the cause of this issue and unable to reproduce it (I tried many ISOs of Windows, every run was successfull).

**Comment by amrbashir** [comment]
Seems like this has been fixed on webview2 side, see https://github.com/tauri-apps/tauri/issues/8196#issuecomment-1897674662

Please update your webview2 version and try again.

**Comment by chirok11** [comment]
No, issue still not resolved, even on mentioned Edge WebView2 version (120.0.2210.144)
[sentry.json](https://github.com/tauri-apps/tauri/files/14071480/sentry.json)

**Comment by chirok11** [comment]
<img width="1493" alt="Снимок экрана 2024-01-27 в 11 35 16" src="https://github.com/tauri-apps/tauri/assets/89095992/4a5ba75e-f43a-47a6-92b8-2b7d24ecad30">
<img width="1489" alt="Снимок экрана 2024-01-27 в 11 35 27" src="https://github.com/tauri-apps/tauri/assets/89095992/62926212-0104-4f20-af9d-e196e4caf0c9">
Too many errors in Sentry with this error.

**Comment by chirok11** [comment]
@amrbashir also, mentioned issue has The group or resource is not in the correct state to perform the requested operation error, they're different, cause of this is high load on system (I saw this error while running heavy computations).

**Comment by chirok11** [comment]
@amrbashir re-open this issue please, or should I create same new? 
Issue still unresolved, here is still many errors in Sentry.

**Comment by jjh42** [comment]
we are also observing this issue, seems to only occur on windows 10.

**Comment by Mati22BE** [comment]
having this issue on windows 11 too
