### ISSUE TITLE
[bug] macOS Intel chips EXC_BAD_ACCESS crash on event listen

### ISSUE THREAD

**Issue by jorge-menjivar** [tauri-apps/tauri#8892]
### Describe the bug

App crashes on macOS (only with Intel chips as far as I can tell) with `EXC_BAD_ACCESS (SIGSEGV)` when using `import { listen } from "@tauri-apps/api/event";` in react useEffect hook.

Adding the following in a react component causes the crash.
```typescript
  const isMounted = useRef(false);

  const startListeners = useCallback(async () => {
    if (isMounted.current) {
      return;
    }
    isMounted.current = true;

    await listen("updates", async () => {
      console.log("It works");
    });
  }, []);

  useEffect(() => {
    startListeners();
  }, [startListeners]);
```

Tested on:
Apple M2 | 14.3.1 (23D60)  --- Runs Okay
Dual-Core Intel Core i7 | 13.6.3 (22G436) --- Crashes
6-Core Intel Core i5 | 14.3 (23D56) -- Crashes

### Reproduction

You can test it with this repo: [https://github.com/jorge-menjivar/tauri-crash-report](https://github.com/jorge-menjivar/tauri-crash-report). A simple build on a mac with an intel chip should reproduce the crash when launching any of the produced apps.

```sh
┌──  macbook:~/js_projects [ ]
└─❯ pnpm create tauri-app --beta
../Library/pnpm/store/v3/tmp/dlx-87650   | Progress: resolved 11, reused 2, downloaded 0, added 2, done
✔ Project name · tauri-app
✔ Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm, bun)
✔ Choose your package manager · pnpm
✔ Choose your UI template · React - (https://react.dev/)
✔ Choose your UI flavor · TypeScript
✔ Would you like to setup the project for mobile as well? · no

Template created! To get started run:
  cd tauri-app
  pnpm install
  pnpm tauri dev

┌──  macbook:~/js_projects [ ] took 25s
└─❯ cd tauri-app

┌──  macbook:~/js_projects/tauri-app [ via  v20.11.0 ]
└─❯ pnpm I
...
```

Modified `identifier` in `./src-tauri/tauri.conf.json`.
Added listener in `./src/providers/App.tsx`.

```sh
┌──  macbook:~/js_projects/tauri-app [ via  v20.11.0 ] took 3s
└─❯ pnpm tauri dev
... Runs OK

┌── macbook:~/js_projects/tauri-app [ via  v20.11.0 ]
└─❯ pnpm tauri build
... Builds OK, but compiled apps will crash on launch
```

### Expected behavior

Not to crash

### Full `tauri info` output

```text
Will crash (Intel chip | node 20.11.0)
[✔] Environment
    - OS: Mac OS 13.6.3 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 20.11.0
    - pnpm: 8.12.0
    - yarn: 1.22.19
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.2
    - tauri-build [RUST]: 2.0.0-beta.1
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.25.0
    - tauri-cli [RUST]: 1.2.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.0
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite

Will crash (Intel chip |node 18.17.0)
[✔] Environment
    - OS: Mac OS 13.6.3 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 18.17.0
    - pnpm: 8.12.0
    - yarn: 1.22.19
    - npm: 10.2.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.2
    - tauri-build [RUST]: 2.0.0-beta.1
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.25.0
    - tauri-cli [RUST]: 1.2.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.0
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite

Will not crash (M2 Chip | node 20.11.0)
[✔] Environment
    - OS: Mac OS 14.3.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.11.0
    - pnpm: 8.15.1
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.2
    - tauri-build [RUST]: 2.0.0-beta.1
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.25.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.0
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

Report from os:

```sh
Process:               tauri-app [3038]
Path:                  /Users/USER/*/tauri-app.app/Contents/MacOS/tauri-app
Identifier:            com.jmenjivar.test
Version:               0.0.0 (20240218.232022)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-02-18 15:21:33.7788 -0800
OS Version:            macOS 13.6.3 (22G436)
Report Version:        12
Anonymous UUID:        DA8C12D7-FB3A-87FD-FE8C-C4B7556411EA


Time Awake Since Boot: 170000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  main  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Codes:       0x0000000000000001, 0x0000000000000020

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [3038]
```

Full report: [report.txt](https://github.com/tauri-apps/tauri/files/14325012/Tauri.bug.apple.crash.report.txt)

**Comment by jorge-menjivar** [comment]
Report from os:

```sh
Process:               tauri-app [3038]
Path:                  /Users/USER/*/tauri-app.app/Contents/MacOS/tauri-app
Identifier:            com.jmenjivar.test
Version:               0.0.0 (20240218.232022)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-02-18 15:21:33.7788 -0800
OS Version:            macOS 13.6.3 (22G436)
Report Version:        12
Anonymous UUID:        DA8C12D7-FB3A-87FD-FE8C-C4B7556411EA


Time Awake Since Boot: 170000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  main  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Codes:       0x0000000000000001, 0x0000000000000020

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [3038]
```

Full report: [report.txt](https://github.com/tauri-apps/tauri/files/14325012/Tauri.bug.apple.crash.report.txt)

**Comment by pewsheen** [comment]
Thanks for the report. The issue should be fixed in https://github.com/tauri-apps/tauri/issues/8645 and will be released in the next version.

**Comment by jorge-menjivar** [comment]
@pewsheen Thank you, I will keep an eye on the update and test again once it is released.

**Comment by karelinaas** [comment]
Has this still not been fixed? Downloaded the last app version today and got the issue as well.

macOS 14.1.1 (23B81)
Quad-Core Intel Core i5

**Comment by jorge-menjivar** [comment]
@karelinaas It was fixed. Maybe it resurfaced again?

**Comment by pewsheen** [comment]
@karelinaas Could you create a new issue for it? In case another reason causes it.
